/**
 * Cooked with Flambe
 * https://github.com/aduros/flambe
 */
'use strict';(function(){var n,y,s,k,m,g,x,e,B,h,u,b,p,l,q,a;function v(c,j){function a(){}a.prototype=c;var t=new a,b;for(b in j)t[b]=j[b];return t}function H(c){return c instanceof Array?function(){return o.iter(c)}:"function"==typeof c.iterator?C(c,c.iterator):c.iterator}function C(c,j){null==j.__id__&&(j.__id__=M++);var a;null==c.hx__closures__?c.hx__closures__={}:a=c.hx__closures__[j.__id__];null==a&&(a=function(){return a.method.apply(a.scope,arguments)},a.scope=c,a.method=j,c.hx__closures__[j.__id__]=
a);return a}var f=function(){return s.__string_rec(this,"")},z=function(c,j){j=j.split("u").join("");this.r=RegExp(c,j)};z.__name__=!0;z.prototype={matchedPos:function(){if(null==this.r.m)throw"No string matched";return{pos:this.r.m.index,len:this.r.m[0].length}},matched:function(c){if(null!=this.r.m&&0<=c&&c<this.r.m.length)c=this.r.m[c];else throw"EReg::matched";return c},match:function(c){this.r.global&&(this.r.lastIndex=0);this.r.m=this.r.exec(c);this.r.s=c;return null!=this.r.m},__class__:z};
var o=function(){};o.__name__=!0;o.cca=function(c,j){var a=c.charCodeAt(j);return a!=a?void 0:a};o.substr=function(c,j,a){if(null!=j&&0!=j&&null!=a&&0>a)return"";null==a&&(a=c.length);0>j?(j=c.length+j,0>j&&(j=0)):0>a&&(a=c.length+a-j);return c.substr(j,a)};o.remove=function(c,j){for(var a=0,t=c.length;a<t;){if(c[a]==j)return c.splice(a,1),!0;a++}return!1};o.iter=function(c){return{cur:0,arr:c,hasNext:function(){return this.cur<this.arr.length},next:function(){return this.arr[this.cur++]}}};var D=
function(){};D.__name__=!0;D.array=function(c){for(var j=[],c=H(c)();c.hasNext();){var a=c.next();j.push(a)}return j};D.count=function(c,j){var a=0;if(null==j)for(var t=H(c)();t.hasNext();)t.next(),a++;else for(t=H(c)();t.hasNext();){var b=t.next();j(b)&&a++}return a};var E=function(){};E.__name__=!0;var A=function(){};A.__name__=!0;A.field=function(c,j){var a=null;try{a=c[j]}catch(b){}return a};A.fields=function(c){var j=[];if(null!=c){var a=Object.prototype.hasOwnProperty,b;for(b in c)"__id__"!=
b&&"hx__closures__"!=b&&a.call(c,b)&&j.push(b)}return j};var w=function(){};w.__name__=!0;w.string=function(c){return s.__string_rec(c,"")};w.parseInt=function(c){var j=parseInt(c,10);if(0==j&&(120==o.cca(c,1)||88==o.cca(c,1)))j=parseInt(c);return isNaN(j)?null:j};w.parseFloat=function(c){return parseFloat(c)};var G=function(){this.b=""};G.__name__=!0;G.prototype={addSub:function(c,j,a){this.b+=null==a?o.substr(c,j,null):o.substr(c,j,a)},__class__:G};var F=function(){};F.__name__=!0;F.main=function(){m.init();
m.hidden.get_changed().connect(function(){null});var c=g.Manifest.build("bootstrap"),c=m._platform.loadAssetPack(c);c.get(F.onSuccess);c.error.connect(function(){null});c.progressChanged.connect(function(){null})};F.onSuccess=function(c){m.root.addChild((new x).add(new e.FillSprite(3158064,m._platform.getStage().get_width(),m._platform.getStage().get_height())));for(var a=(new e.tileSheet.TileSheetHelper).prepareAnimTexture(c.getFile("remiWalk.json",!0)),d=0;500>d;){d++;var b=new x,i=new e.tileSheet.AnimSprite(c.getTexture("remiWalk"));
i.initialize(a);i.addSequence("all",[0,1,2,3,4,5,6,7,8,9,10,11],24);i.play("all");i.centerAnchor();b.add(i);i=b._compMap.Sprite_1;i.x.set__(Math.random()*(m._platform.getStage().get_width()-i.getNaturalWidth()));i.y.set__(Math.random()*(m._platform.getStage().get_height()-i.getNaturalHeight()));m.root.addChild(b)}c=new e.Font(c,"tinyfont");m.root.addChild((new x).add(new e.TextSprite(c)).add(new B.FpsDisplay))};m=void 0;g=void 0;x=void 0;e=void 0;B=void 0;h=void 0;u=void 0;b=void 0;p=void 0;l=void 0;
q=void 0;a=void 0;l=void 0;l=void 0;h={Disposable:function(){}};h.Disposable.__name__=!0;u=function(){};u.__name__=!0;u.__interfaces__=[h.Disposable];u.prototype={init:function(c,a){this.owner=c;this.next=a},get_name:function(){return null},dispose:function(){null!=this.owner&&this.owner.remove(this)},onUpdate:function(){},onRemoved:function(){},onAdded:function(){},__class__:u};x=function(){this.parent=this.firstChild=this.next=this.firstComponent=null;this._compMap={}};x.__name__=!0;x.__interfaces__=
[h.Disposable];x.prototype={dispose:function(){for(null!=this.parent&&this.parent.removeChild(this);null!=this.firstComponent;)this.firstComponent.dispose();this.disposeChildren()},disposeChildren:function(){for(;null!=this.firstChild;)this.firstChild.dispose()},removeChild:function(c){for(var a=null,d=this.firstChild;null!=d;){var b=d.next;if(d==c){null==a?this.firstChild=b:a.next=b;d.parent=null;d.next=null;break}a=d;d=b}},addChild:function(c,a){null==a&&(a=!0);null!=c.parent&&c.parent.removeChild(c);
c.parent=this;if(a){for(var d=null,b=this.firstChild;null!=b;)d=b,b=b.next;null!=d?d.next=c:this.firstChild=c}else c.next=this.firstChild,this.firstChild=c;return this},remove:function(c){for(var a=null,d=this.firstComponent;null!=d;){var b=d.next;if(d==c){null==a?this.firstComponent=b:a.init(this,b);delete this._compMap[d.get_name()];d.onRemoved();d.init(null,null);break}a=d;d=b}},add:function(c){c.dispose();var a=c.get_name(),d=this._compMap[a];null!=d&&this.remove(d);this._compMap[a]=c;a=null;
for(d=this.firstComponent;null!=d;)a=d,d=d.next;null!=a?a.next=c:this.firstComponent=c;c.init(this,null);c.onAdded();return this},__class__:x};b={Platform:function(){}};b.Platform.__name__=!0;b.Platform.prototype={__class__:b.Platform};b.html={};b.html.HtmlPlatform=function(){};b.html.HtmlPlatform.__name__=!0;b.html.HtmlPlatform.__interfaces__=[b.Platform];b.html.HtmlPlatform.prototype={createRenderer:function(c){return new b.html.CanvasRenderer(c)},getY:function(c,a){return this._stage.scaleFactor*
(c.clientY-a.top)},getX:function(c,a){return this._stage.scaleFactor*(c.clientX-a.left)},getRenderer:function(){return this._renderer},update:function(c){var a=(c-this._lastUpdate)/1E3;this._lastUpdate=c;this._skipFrame?this._skipFrame=!1:(this.mainLoop.update(a),this.mainLoop.render(this._renderer))},getStage:function(){return this._stage},loadAssetPack:function(c){return(new b.html.HtmlAssetPackLoader(this,c)).promise},init:function(){var c=this,a=null;try{a=k.window.flambe.canvas}catch(d){}a.setAttribute("tabindex",
"0");a.style.outlineStyle="none";a.setAttribute("moz-opaque","true");this._stage=new b.html.HtmlStage(a);this._pointer=new b.BasicPointer;this._mouse=new b.html.HtmlMouse(this._pointer,a);this._keyboard=new b.BasicKeyboard;this._renderer=this.createRenderer(a);m.hasGPU.set__(!0);this.mainLoop=new b.MainLoop;this._container=a.parentElement;this._container.style.overflow="hidden";this._container.style.position="relative";this._container.style.msTouchAction="none";var t=0,i=function(d){if(!(1E3>d.timeStamp-
t)){var b=a.getBoundingClientRect(),e=c.getX(d,b),b=c.getY(d,b);switch(d.type){case "mousedown":d.target==a&&(d.preventDefault(),c._mouse.submitDown(e,b,d.button),a.focus());break;case "mousemove":c._mouse.submitMove(e,b);break;case "mouseup":c._mouse.submitUp(e,b,d.button);break;case "mousewheel":case "DOMMouseScroll":c._mouse.submitScroll(e,b,"mousewheel"==d.type?d.wheelDelta/40:-d.detail)&&d.preventDefault()}}};k.window.addEventListener("mousedown",i,!1);k.window.addEventListener("mousemove",i,
!1);k.window.addEventListener("mouseup",i,!1);a.addEventListener("mousewheel",i,!1);a.addEventListener("DOMMouseScroll",i,!1);var e="undefined"!=typeof k.window.ontouchstart,i="msMaxTouchPoints"in window.navigator&&1<window.navigator.msMaxTouchPoints;if(e||i){var f=new b.BasicTouch(this._pointer,e?4:k.navigator.msMaxTouchPoints);this._touch=f;i=function(a){var j=e?a.changedTouches:[a],d=a.target.getBoundingClientRect();t=a.timeStamp;switch(a.type){case "touchstart":case "MSPointerDown":a.preventDefault();
b.html.HtmlUtil.SHOULD_HIDE_MOBILE_BROWSER&&b.html.HtmlUtil.hideMobileBrowser();for(a=0;a<j.length;){var i=j[a];++a;var h=c.getX(i,d),g=c.getY(i,d),i=(e?i.identifier:i.pointerId)|0;f.submitDown(i,h,g)}break;case "touchmove":case "MSPointerMove":a.preventDefault();for(a=0;a<j.length;)i=j[a],++a,h=c.getX(i,d),g=c.getY(i,d),i=(e?i.identifier:i.pointerId)|0,f.submitMove(i,h,g);break;case "touchend":case "touchcancel":case "MSPointerUp":for(a=0;a<j.length;)i=j[a],++a,h=c.getX(i,d),g=c.getY(i,d),i=(e?i.identifier:
i.pointerId)|0,f.submitUp(i,h,g)}};e?(a.addEventListener("touchstart",i,!1),a.addEventListener("touchmove",i,!1),a.addEventListener("touchend",i,!1),a.addEventListener("touchcancel",i,!1)):(a.addEventListener("MSPointerDown",i,!1),a.addEventListener("MSPointerMove",i,!1),a.addEventListener("MSPointerUp",i,!1))}else this._touch=new b.DummyTouch;i=function(a){switch(a.type){case "keydown":c._keyboard.submitDown(a.keyCode)&&a.preventDefault();break;case "keyup":c._keyboard.submitUp(a.keyCode)}};a.addEventListener("keydown",
i,!1);a.addEventListener("keyup",i,!1);var h=k.window.onerror;k.window.onerror=function(c,a,j){m.uncaughtError.emit1(c);return null!=h?h(c,a,j):!1};var g=b.html.HtmlUtil.loadExtension("hidden",k.document);null!=g.value&&(i=function(){m.hidden.set__(A.field(k.document,g.field))},i(null),k.document.addEventListener(g.prefix+"visibilitychange",i,!1),m.hidden.get_changed().connect(function(a){a||(c._skipFrame=!0)}));this._lastUpdate=Date.now();this._skipFrame=!1;var I=b.html.HtmlUtil.loadExtension("requestAnimationFrame").value;
if(null!=I){var l=k.window.performance,n=null!=l&&b.html.HtmlUtil.polyfill("now",l);n?this._lastUpdate=l.now():null;var q=null,q=function(d){c.update(n?l.now():d);I(q,a)};I(q,a)}else k.window.setInterval(function(){c.update(Date.now())},16)},__class__:b.html.HtmlPlatform};h.Value=function(c,a){this._value=c;null!=a&&(this._changed=new h.Signal2(a))};h.Value.__name__=!0;h.Value.prototype={get_changed:function(){null==this._changed&&(this._changed=new h.Signal2);return this._changed},set__:function(c){var a=
this._value;c!=a&&(this._value=c,null!=this._changed&&this._changed.emit2(c,a));return c},watch:function(c){c(this._value,this._value);return this.get_changed().connect(c)},__class__:h.Value};h.SignalConnection=function(c,a){this._next=null;this._signal=c;this._listener=a;this.stayInList=!0};h.SignalConnection.__name__=!0;h.SignalConnection.__interfaces__=[h.Disposable];h.SignalConnection.prototype={dispose:function(){null!=this._signal&&(this._signal.disconnect(this),this._signal=null)},once:function(){this.stayInList=
!1;return this},__class__:h.SignalConnection};h.SignalBase=function(c){this._head=null!=c?new h.SignalConnection(this,c):null;this._deferredTasks=null};h.SignalBase.__name__=!0;h.SignalBase.prototype={listRemove:function(c){for(var a=null,d=this._head;null!=d;){if(d==c){c=d._next;null==a?this._head=c:a._next=c;break}a=d;d=d._next}},listAdd:function(c,a){if(a)c._next=this._head,this._head=c;else{for(var d=null,b=this._head;null!=b;)d=b,b=b._next;null!=d?d._next=c:this._head=c}},didEmit:function(c){for(this._head=
c;null!=this._deferredTasks;)this._deferredTasks.fn(),this._deferredTasks=this._deferredTasks.next},willEmit:function(){var c=this._head;this._head=h.SignalBase.DISPATCHING_SENTINEL;return c},defer:function(c){for(var a=null,d=this._deferredTasks;null!=d;)a=d,d=d.next;c=new h._SignalBase.Task(c);null!=a?a.next=c:this._deferredTasks=c},emit2:function(c,a){for(var d=this.willEmit(),b=d;null!=b;)b._listener(c,a),b.stayInList||b.dispose(),b=b._next;this.didEmit(d)},emit1:function(c){for(var a=this.willEmit(),
d=a;null!=d;)d._listener(c),d.stayInList||d.dispose(),d=d._next;this.didEmit(a)},emit0:function(){for(var c=this.willEmit(),a=c;null!=a;)a._listener(),a.stayInList||a.dispose(),a=a._next;this.didEmit(c)},disconnect:function(c){var a=this;this._head==h.SignalBase.DISPATCHING_SENTINEL?this.defer(function(){a.listRemove(c)}):this.listRemove(c)},connectImpl:function(c,a){var d=this,b=new h.SignalConnection(this,c);this._head==h.SignalBase.DISPATCHING_SENTINEL?this.defer(function(){d.listAdd(b,a)}):this.listAdd(b,
a);return b},__class__:h.SignalBase};h.Signal2=function(c){h.SignalBase.call(this,c)};h.Signal2.__name__=!0;h.Signal2.__super__=h.SignalBase;h.Signal2.prototype=v(h.SignalBase.prototype,{connect:function(c,a){null==a&&(a=!1);return this.connectImpl(c,a)},__class__:h.Signal2});h.Signal1=function(c){h.SignalBase.call(this,c)};h.Signal1.__name__=!0;h.Signal1.__super__=h.SignalBase;h.Signal1.prototype=v(h.SignalBase.prototype,{connect:function(c,a){null==a&&(a=!1);return this.connectImpl(c,a)},__class__:h.Signal1});
p={AnimatedFloat:function(c,a){h.Value.call(this,c,a)}};p.AnimatedFloat.__name__=!0;p.AnimatedFloat.__super__=h.Value;p.AnimatedFloat.prototype=v(h.Value.prototype,{update:function(c){null!=this._behavior&&(h.Value.prototype.set__.call(this,this._behavior.update(c)),this._behavior.isComplete()&&(this._behavior=null))},set__:function(c){this._behavior=null;return h.Value.prototype.set__.call(this,c)},__class__:p.AnimatedFloat});m=function(){};m.__name__=!0;m.init=function(){m._calledInit||(m._platform.init(),
m._calledInit=!0)};l=function(){this._realDt=0};l.__name__=!0;l.__super__=u;l.prototype=v(u.prototype,{onUpdate:function(c){0<this._realDt&&(c=this._realDt,this._realDt=0);this.scale.update(c)},get_name:function(){return"SpeedAdjuster_5"},__class__:l});p.Behavior=function(){};p.Behavior.__name__=!0;p.Behavior.prototype={__class__:p.Behavior};g={AssetFormat:{__ename__:!0,__constructs__:"WEBP,JXR,PNG,JPG,GIF,MP3,M4A,OGG,WAV,Data".split(",")}};g.AssetFormat.WEBP=["WEBP",0];g.AssetFormat.WEBP.toString=
f;g.AssetFormat.WEBP.__enum__=g.AssetFormat;g.AssetFormat.JXR=["JXR",1];g.AssetFormat.JXR.toString=f;g.AssetFormat.JXR.__enum__=g.AssetFormat;g.AssetFormat.PNG=["PNG",2];g.AssetFormat.PNG.toString=f;g.AssetFormat.PNG.__enum__=g.AssetFormat;g.AssetFormat.JPG=["JPG",3];g.AssetFormat.JPG.toString=f;g.AssetFormat.JPG.__enum__=g.AssetFormat;g.AssetFormat.GIF=["GIF",4];g.AssetFormat.GIF.toString=f;g.AssetFormat.GIF.__enum__=g.AssetFormat;g.AssetFormat.MP3=["MP3",5];g.AssetFormat.MP3.toString=f;g.AssetFormat.MP3.__enum__=
g.AssetFormat;g.AssetFormat.M4A=["M4A",6];g.AssetFormat.M4A.toString=f;g.AssetFormat.M4A.__enum__=g.AssetFormat;g.AssetFormat.OGG=["OGG",7];g.AssetFormat.OGG.toString=f;g.AssetFormat.OGG.__enum__=g.AssetFormat;g.AssetFormat.WAV=["WAV",8];g.AssetFormat.WAV.toString=f;g.AssetFormat.WAV.__enum__=g.AssetFormat;g.AssetFormat.Data=["Data",9];g.AssetFormat.Data.toString=f;g.AssetFormat.Data.__enum__=g.AssetFormat;g.AssetEntry=function(c,a,d,b){this.name=c;this.url=a;this.format=d;this.bytes=b};g.AssetEntry.__name__=
!0;g.AssetEntry.prototype={__class__:g.AssetEntry};g.AssetPack=function(){};g.AssetPack.__name__=!0;g.AssetPack.prototype={__class__:g.AssetPack};s=void 0;k=void 0;s=function(){};s.__name__=!0;s.__string_rec=function(c,a){if(null==c)return"null";if(5<=a.length)return"<...>";var d=typeof c;if("function"==d&&(c.__name__||c.__ename__))d="object";switch(d){case "object":if(c instanceof Array){if(c.__enum__){if(2==c.length)return c[0];for(var d=c[0]+"(",a=a+"\t",b=2,i=c.length;b<i;)var e=b++,d=2!=e?d+
(","+s.__string_rec(c[e],a)):d+s.__string_rec(c[e],a);return d+")"}b=c.length;d="[";a+="\t";for(i=0;i<b;)e=i++,d+=(0<e?",":"")+s.__string_rec(c[e],a);return d+"]"}try{i=c.toString}catch(f){return"???"}if(null!=i&&i!=Object.toString&&(d=c.toString(),"[object Object]"!=d))return d;i=null;d="{\n";a+="\t";b=null!=c.hasOwnProperty;for(i in c)if(!b||c.hasOwnProperty(i))"prototype"==i||"__class__"==i||"__super__"==i||"__interfaces__"==i||"__properties__"==i||(2!=d.length&&(d+=", \n"),d+=a+i+" : "+s.__string_rec(c[i],
a));a=a.substring(1);return d+("\n"+a+"}");case "function":return"<function>";case "string":return c;default:return""+c}};s.__interfLoop=function(c,a){if(null==c)return!1;if(c==a)return!0;var d=c.__interfaces__;if(null!=d)for(var b=0,i=d.length;b<i;){var e=b++,e=d[e];if(e==a||s.__interfLoop(e,a))return!0}return s.__interfLoop(c.__super__,a)};s.__instanceof=function(c,a){if(null==a)return!1;switch(a){case N:return(c|0)===c;case K:return"number"==typeof c;case L:return"boolean"==typeof c;case String:return"string"==
typeof c;case O:return!0;default:if(null!=c){if("function"==typeof a){if(c instanceof a)return a==Array?null==c.__enum__:!0;if(s.__interfLoop(c.__class__,a))return!0}}else return!1;if(a==P&&null!=c.__name__)return!0;null;if(a==Q&&null!=c.__ename__)return!0;null;return c.__enum__==a}};s.__cast=function(c,a){if(s.__instanceof(c,a))return c;throw"Cannot cast "+w.string(c)+" to "+w.string(a);};h.Strings=function(){};h.Strings.__name__=!0;h.Strings.getFileExtension=function(c){var a=c.lastIndexOf(".");
return 0<a?o.substr(c,a+1,null):null};h.Strings.removeFileExtension=function(c){var a=c.lastIndexOf(".");return 0<a?o.substr(c,0,a):c};h.Strings.getUrlExtension=function(c){var a=c.lastIndexOf("?");0<=a&&(c=o.substr(c,0,a));a=c.lastIndexOf("/");0<=a&&(c=o.substr(c,a+1,null));return h.Strings.getFileExtension(c)};h.Strings.joinPath=function(c,a){47!=c.charCodeAt(c.length-1)&&(c+="/");return c+a};h.Strings.withFields=function(c,a){var d=a.length;if(0<d){for(var c=c+(0<c.length?" [":"["),b=0;b<d;){0<
b&&(c+=", ");var i=a[b],e=a[b+1];if(s.__instanceof(e,Error)){var f=e.stack;null!=f&&(e=f)}c+=i+"="+w.string(e);b+=2}c+="]"}return c};k=function(){};k.__name__=!0;g.Manifest=function(){this._entries=[]};g.Manifest.__name__=!0;g.Manifest.build=function(c,a){null==a&&(a=!0);var d=g.Manifest._buildManifest.get(c);if(null==d){if(a)throw h.Strings.withFields("Missing asset pack",["name",c]);return null}return d.clone()};g.Manifest.inferFormat=function(c){c=h.Strings.getUrlExtension(c);if(null!=c)switch(c.toLowerCase()){case "gif":return g.AssetFormat.GIF;
case "jpg":case "jpeg":return g.AssetFormat.JPG;case "jxr":return g.AssetFormat.JXR;case "png":return g.AssetFormat.PNG;case "webp":return g.AssetFormat.WEBP;case "m4a":return g.AssetFormat.M4A;case "mp3":return g.AssetFormat.MP3;case "ogg":return g.AssetFormat.OGG;case "wav":return g.AssetFormat.WAV}else null;return g.AssetFormat.Data};g.Manifest.createBuildManifests=function(){var c=new n.StringMap;c.set("bootstrap",[{name:"tinyfont.png",md5:"32988b545c4243b364008800f359ea92",bytes:16702},{name:"tinyfont.fnt",
md5:"6b1f975607029ae74049de5a34e1c816",bytes:22499},{name:"remiWalk.png",md5:"af5ddf9fb90ee12863e4e0b837ac284e",bytes:30194},{name:"remiWalk.json",md5:"561f11a97e4672c424ed6ddb5dd7f8b8",bytes:2528},{name:"box.png",md5:"3cc1b7e9fd3fea3e2b460eb6fbbba4ff",bytes:7820},{name:"ball.png",md5:"025c34b8e67dbc2969adec7073614b22",bytes:2964}]);for(var a=new n.StringMap,d=c.keys();d.hasNext();){var b=d.next(),e=new g.Manifest;e.set_relativeBasePath("assets");for(var f=0,J=c.get(b);f<J.length;){var r=J[f];++f;
var k=r.name,l=b+"/"+k+"?v="+w.string(r.md5),m=g.Manifest.inferFormat(k);m!=g.AssetFormat.Data&&(k=h.Strings.removeFileExtension(k));e.add(k,l,r.bytes,m)}a.set(b,e)}return a};g.Manifest.prototype={set_externalBasePath:function(c){this._externalBasePath=c;null!=c&&null;return c},get_externalBasePath:function(){return this._externalBasePath},set_relativeBasePath:function(c){this._relativeBasePath=c;null!=c&&null;return c},get_relativeBasePath:function(){return this._relativeBasePath},getFullURL:function(c){var a=
null!=this.get_externalBasePath()&&g.Manifest._supportsCrossOrigin?this.get_externalBasePath():this.get_relativeBasePath(),d=null!=this.get_externalBasePath()?this.get_externalBasePath():this.get_relativeBasePath();c.format==g.AssetFormat.Data&&(d=a);return null!=d?h.Strings.joinPath(d,c.url):c.url},clone:function(){var c=new g.Manifest;c.set_relativeBasePath(this.get_relativeBasePath());c.set_externalBasePath(this.get_externalBasePath());c._entries=this._entries.slice();return c},iterator:function(){return o.iter(this._entries)},
add:function(c,a,d,b){null==d&&(d=0);null==b&&(b=g.Manifest.inferFormat(a));c=new g.AssetEntry(c,a,b,d);this._entries.push(c);return c},__class__:g.Manifest};B={FpsDisplay:function(){this.reset()}};B.FpsDisplay.__name__=!0;B.FpsDisplay.__super__=u;B.FpsDisplay.prototype=v(u.prototype,{reset:function(){this._fpsTime=this._fpsFrames=0},onUpdate:function(c){++this._fpsFrames;this._fpsTime+=c;if(1<this._fpsTime){var c="FPS: "+(100*(this._fpsFrames/this._fpsTime)|0)/100,a=this.owner._compMap.Sprite_1;
null!=a?a.set_text(c):null;this.reset()}},get_name:function(){return"FpsDisplay_0"},__class__:B.FpsDisplay});e={BlendMode:{__ename__:!0,__constructs__:["Normal","Add","CopyExperimental"]}};e.BlendMode.Normal=["Normal",0];e.BlendMode.Normal.toString=f;e.BlendMode.Normal.__enum__=e.BlendMode;e.BlendMode.Add=["Add",1];e.BlendMode.Add.toString=f;e.BlendMode.Add.__enum__=e.BlendMode;e.BlendMode.CopyExperimental=["CopyExperimental",2];e.BlendMode.CopyExperimental.toString=f;e.BlendMode.CopyExperimental.__enum__=
e.BlendMode;q={Point:function(c,a){null==a&&(a=0);null==c&&(c=0);this.x=c;this.y=a}};q.Point.__name__=!0;q.Point.prototype={__class__:q.Point};e.Sprite=function(){this.blendMode=this.scissor=null;var c=this;this._flags=11;this._localMatrix=new q.Matrix;var a=function(){c._flags|=12};this.x=new p.AnimatedFloat(0,a);this.y=new p.AnimatedFloat(0,a);this.rotation=new p.AnimatedFloat(0,a);this.scaleX=new p.AnimatedFloat(1,a);this.scaleY=new p.AnimatedFloat(1,a);this.anchorX=new p.AnimatedFloat(0,a);this.anchorY=
new p.AnimatedFloat(0,a);this.alpha=new p.AnimatedFloat(1)};e.Sprite.__name__=!0;e.Sprite.hitTest=function(c,a,d){var b=c._compMap.Sprite_1;if(null!=b){if(3!=(b._flags&3))return null;b.getLocalMatrix().inverseTransform(a,d,e.Sprite._scratchPoint)&&(a=e.Sprite._scratchPoint.x,d=e.Sprite._scratchPoint.y);var i=b.scissor;if(null!=i&&!i.contains(a,d))return null}c=e.Sprite.hitTestBackwards(c.firstChild,a,d);return null!=c?c:null!=b&&b.containsLocal(a,d)?b:null};e.Sprite.render=function(c,a){var d=c._compMap.Sprite_1;
if(null!=d){var b=d.alpha._value;if(0==(d._flags&1)||0>=b)return;a.save();1>b&&a.multiplyAlpha(b);null!=d.blendMode&&a.setBlendMode(d.blendMode);b=d.getLocalMatrix();a.transform(b.m00,b.m10,b.m01,b.m11,b.m02,b.m12);b=d.scissor;null!=b&&a.applyScissor(b.x,b.y,b.width,b.height);d.draw(a)}b=c._compMap.Director_3;if(null!=b)for(var b=b.occludedScenes,i=0;i<b.length;){var f=b[i];++i;e.Sprite.render(f,a)}for(b=c.firstChild;null!=b;)i=b.next,e.Sprite.render(b,a),b=i;null!=d&&a.restore()};e.Sprite.hitTestBackwards=
function(c,a,d){if(null!=c){var b=e.Sprite.hitTestBackwards(c.next,a,d);return null!=b?b:e.Sprite.hitTest(c,a,d)}return null};e.Sprite.__super__=u;e.Sprite.prototype=v(u.prototype,{draw:function(){},onUpdate:function(c){this.x.update(c);this.y.update(c);this.rotation.update(c);this.scaleX.update(c);this.scaleY.update(c);this.alpha.update(c);this.anchorX.update(c);this.anchorY.update(c)},centerAnchor:function(){this.anchorX.set__(this.getNaturalWidth()/2);this.anchorY.set__(this.getNaturalHeight()/
2);return this},getLocalMatrix:function(){0!=(this._flags&4)&&(this._flags&=-5,this._localMatrix.compose(this.x._value,this.y._value,this.scaleX._value,this.scaleY._value,3.141592653589793*this.rotation._value/180),this._localMatrix.translate(-this.anchorX._value,-this.anchorY._value));return this._localMatrix},containsLocal:function(c,a){return 0<=c&&c<this.getNaturalWidth()&&0<=a&&a<this.getNaturalHeight()},getNaturalHeight:function(){return 0},getNaturalWidth:function(){return 0},get_name:function(){return"Sprite_1"},
__class__:e.Sprite});e.FillSprite=function(c,a,d){e.Sprite.call(this);this.color=c;this.width=new p.AnimatedFloat(a);this.height=new p.AnimatedFloat(d)};e.FillSprite.__name__=!0;e.FillSprite.__super__=e.Sprite;e.FillSprite.prototype=v(e.Sprite.prototype,{onUpdate:function(c){e.Sprite.prototype.onUpdate.call(this,c);this.width.update(c);this.height.update(c)},getNaturalHeight:function(){return this.height._value},getNaturalWidth:function(){return this.width._value},draw:function(c){c.fillRect(this.color,
0,0,this.width._value,this.height._value)},__class__:e.FillSprite});e.Glyph=function(c){this._kernings=null;this.xOffset=this.yOffset=this.xAdvance=0;this.page=null;this.x=this.y=this.width=this.height=0;this.charCode=c};e.Glyph.__name__=!0;e.Glyph.prototype={setKerning:function(c,a){null==this._kernings&&(this._kernings=new n.IntMap);this._kernings.set(c,a)},getKerning:function(c){return null!=this._kernings?this._kernings.get(c)|0:0},draw:function(c,a,d){0<this.width&&c.drawSubImage(this.page,a+
this.xOffset,d+this.yOffset,this.x,this.y,this.width,this.height)},__class__:e.Glyph};e.Font=function(c,a){this.name=a;this._glyphs=new n.IntMap;this._glyphs.set(e.Font.NEWLINE.charCode,e.Font.NEWLINE);for(var d=new e._Font.ConfigParser(c.getFile(a+".fnt")),b=new n.IntMap,i=a.lastIndexOf("/"),i=0<=i?o.substr(a,0,i+1):"",f=d.keywords();f.hasNext();)switch(f.next()){case "info":for(var g=d.pairs();g.hasNext();){var r=g.next();switch(r.key){case "size":this.size=r.getInt()}}break;case "page":for(var g=
0,k=null,l=d.pairs();l.hasNext();)switch(r=l.next(),r.key){case "id":g=r.getInt();break;case "file":k=r.getString()}b.set(g,c.getTexture(i+h.Strings.removeFileExtension(k)));break;case "char":g=null;for(k=d.pairs();k.hasNext();)switch(r=k.next(),r.key){case "id":g=new e.Glyph(r.getInt());break;case "x":g.x=r.getInt();break;case "y":g.y=r.getInt();break;case "width":g.width=r.getInt();break;case "height":g.height=r.getInt();break;case "page":g.page=b.get(r.getInt());break;case "xoffset":g.xOffset=
r.getInt();break;case "yoffset":g.yOffset=r.getInt();break;case "xadvance":g.xAdvance=r.getInt()}this._glyphs.set(g.charCode,g);break;case "kerning":g=null;k=-1;for(l=d.pairs();l.hasNext();)switch(r=l.next(),r.key){case "first":g=this._glyphs.get(r.getInt());break;case "second":k=r.getInt();break;case "amount":g.setKerning(k,r.getInt())}}};e.Font.__name__=!0;e.Font.prototype={layoutText:function(a,j,b){null==b&&(b=0);null==j&&(j=e.TextAlign.Left);return new e.TextLayout(this,a,j,b)},__class__:e.Font};
e.TextAlign={__ename__:!0,__constructs__:["Left","Center","Right"]};e.TextAlign.Left=["Left",0];e.TextAlign.Left.toString=f;e.TextAlign.Left.__enum__=e.TextAlign;e.TextAlign.Center=["Center",1];e.TextAlign.Center.toString=f;e.TextAlign.Center.__enum__=e.TextAlign;e.TextAlign.Right=["Right",2];e.TextAlign.Right.toString=f;e.TextAlign.Right.__enum__=e.TextAlign;e.TextLayout=function(a,j,b,t){this.lines=0;var i=this;this._font=a;this._glyphs=[];this._offsets=[];this.bounds=new q.Rectangle;for(var f=
[],g=j.length,h=0;h<g;){var k=h++,l=j.charCodeAt(k),l=a._glyphs.get(l);null!=l?this._glyphs.push(l):null}for(var j=-1,m=0,n=0,g=a._glyphs.get(10),h=function(){i.bounds.width=q.FMath.max(i.bounds.width,m);i.bounds.height+=n;f[i.lines]=m;n=m=0;++i.lines},k=0;k<this._glyphs.length;){l=this._glyphs[k];this._offsets[k]=m;var o=0<t&&m+l.width>t;o||l==g?(o&&(0<=j?(this._glyphs[j]=g,m=this._offsets[j],k=j):this._glyphs.splice(k,0,g)),j=-1,n=a.size,h()):(32==l.charCode&&(j=k),m+=l.xAdvance,n=q.FMath.max(n,
l.height+l.yOffset),k+1<this._glyphs.length&&(m+=l.getKerning(this._glyphs[k+1].charCode)));++k}h();for(var k=0,j=e.TextLayout.getAlignOffset(b,f[0],t),g=1.79769313486231E308,h=-1.79769313486231E308,p=o=0,u=this._glyphs.length;p<u;){l=this._glyphs[p];10==l.charCode&&(k+=a.size,++o,j=e.TextLayout.getAlignOffset(b,f[o],t));this._offsets[p]+=j;var s=k+l.yOffset,g=g<s?g:s,h=q.FMath.max(h,s+l.height);++p}this.bounds.x=e.TextLayout.getAlignOffset(b,this.bounds.width,t);this.bounds.y=g;this.bounds.height=
h-g};e.TextLayout.__name__=!0;e.TextLayout.getAlignOffset=function(a,j,b){switch(a[1]){case 0:return 0;case 2:return b-j;case 1:return(b-j)/2}};e.TextLayout.prototype={draw:function(a){for(var j=0,b=0,e=this._glyphs.length;b<e;){var i=this._glyphs[b];10==i.charCode?j+=this._font.size:i.draw(a,this._offsets[b],j);++b}},__class__:e.TextLayout};e._Font={};e._Font.ConfigParser=function(a){this._configText=a;this._keywordPattern=new z("([a-z]+)(.*)","");this._pairPattern=new z('([a-z]+)=("[^"]*"|[^\\s]+)',
"")};e._Font.ConfigParser.__name__=!0;e._Font.ConfigParser.advance=function(a,b){var d=b.matchedPos();return o.substr(a,d.pos+d.len,a.length)};e._Font.ConfigParser.prototype={pairs:function(){var a=this,b=this._pairText;return{next:function(){b=e._Font.ConfigParser.advance(b,a._pairPattern);return new e._Font.ConfigPair(a._pairPattern.matched(1),a._pairPattern.matched(2))},hasNext:function(){return a._pairPattern.match(b)}}},keywords:function(){var a=this,b=this._configText;return{next:function(){b=
e._Font.ConfigParser.advance(b,a._keywordPattern);a._pairText=a._keywordPattern.matched(2);return a._keywordPattern.matched(1)},hasNext:function(){return a._keywordPattern.match(b)}}},__class__:e._Font.ConfigParser};e._Font.ConfigPair=function(a,b){this.key=a;this._value=b};e._Font.ConfigPair.__name__=!0;e._Font.ConfigPair.prototype={getString:function(){return 34!=this._value.charCodeAt(0)?null:o.substr(this._value,1,this._value.length-2)},getInt:function(){return w.parseInt(this._value)},__class__:e._Font.ConfigPair};
e.Graphics=function(){};e.Graphics.__name__=!0;e.Graphics.prototype={__class__:e.Graphics};e.Orientation={__ename__:!0,__constructs__:["Portrait","Landscape"]};e.Orientation.Portrait=["Portrait",0];e.Orientation.Portrait.toString=f;e.Orientation.Portrait.__enum__=e.Orientation;e.Orientation.Landscape=["Landscape",1];e.Orientation.Landscape.toString=f;e.Orientation.Landscape.__enum__=e.Orientation;e.Stage=function(){};e.Stage.__name__=!0;e.Stage.prototype={__class__:e.Stage};e.TextSprite=function(a,
b){null==b&&(b="");this._layout=null;var d=this;e.Sprite.call(this);this._font=a;this._text=b;this._align=e.TextAlign.Left;this._flags|=32;this.wrapWidth=new p.AnimatedFloat(0,function(){d._flags|=32})};e.TextSprite.__name__=!0;e.TextSprite.__super__=e.Sprite;e.TextSprite.prototype=v(e.Sprite.prototype,{onUpdate:function(a){e.Sprite.prototype.onUpdate.call(this,a);this.wrapWidth.update(a)},updateLayout:function(){0!=(this._flags&32)&&(this._flags&=-33,this._layout=this._font.layoutText(this._text,
this._align,this.wrapWidth._value))},set_text:function(a){this._text=a;this._flags|=32;return a},containsLocal:function(a,b){this.updateLayout();return this._layout.bounds.contains(a,b)},getNaturalHeight:function(){this.updateLayout();return this._layout.lines*this._font.size},getNaturalWidth:function(){this.updateLayout();return 0<this.wrapWidth._value?this.wrapWidth._value:this._layout.bounds.width},draw:function(a){this.updateLayout();this._layout.draw(a,this._align)},__class__:e.TextSprite});
e.Texture=function(){};e.Texture.__name__=!0;e.tileSheet={};e.tileSheet.AnimSeqData=function(a,b,d,e){null==e&&(e=!0);null==d&&(d=0);this.seqName=a;this.delay=0;0<d&&(this.delay=1/d);this.arFrames=b;this.loop=e};e.tileSheet.AnimSeqData.__name__=!0;e.tileSheet.AnimSeqData.prototype={__class__:e.tileSheet.AnimSeqData};e.tileSheet.AnimSprite=function(a){e.Sprite.call(this);this.fakeElapsed=0.0167;this.frameTimer=0;this.mSequences=[];this.texture=a};e.tileSheet.AnimSprite.__name__=!0;e.tileSheet.AnimSprite.__super__=
e.Sprite;e.tileSheet.AnimSprite.prototype=v(e.Sprite.prototype,{getNaturalHeight:function(){return this.mAnimSheet.get_frameHeight(this.curIndex)},getNaturalWidth:function(){return this.mAnimSheet.get_frameWidth(this.curIndex)},draw:function(a){var b=this.mAnimSheet.getFrameData(this.curIndex);a.drawSubImage(this.texture,b.offX,b.offY,b.x,b.y,b.w,b.h)},drawFrameInternal:function(){this.dirty=!1},advanceFrame:function(){(this.curFrame|0)==this.curAnim.arFrames.length-1?this.curAnim.loop?this.curFrame=
0:this.donePlaying=!0:++this.curFrame;this.curIndex=this.curAnim.arFrames[this.curFrame];this.dirty=!0},updateAnimation:function(){if(null!=this.curAnim&&0<this.curAnim.delay&&!this.donePlaying)for(this.frameTimer+=this.fakeElapsed;this.frameTimer>this.curAnim.delay;)this.frameTimer-=this.curAnim.delay,this.advanceFrame();this.dirty&&this.drawFrameInternal()},onUpdate:function(a){e.Sprite.prototype.onUpdate.call(this,a);this.updateAnimation()},drawFrame:function(a){null==a&&(a=!1);(a||this.dirty)&&
this.drawFrameInternal()},play:function(a){null==a?(this.donePlaying=!1,this.dirty=!0,this.frameTimer=0):(this.frameTimer=this.curIndex=this.curFrame=0,this.curAnim=this.findSequenceByName(a),null!=this.curAnim&&(this.curIndex=this.curAnim.arFrames[0],this.donePlaying=!1,this.dirty=!0,1==this.curAnim.arFrames.length&&(this.donePlaying=!0)))},findSequenceByName:function(a){for(var b,d=0;d<this.mSequences.length;){b=s.__cast(this.mSequences[d],e.tileSheet.AnimSeqData);if(b.seqName==a)return b;d++}return null},
addSequence:function(a,b,d,t){null==t&&(t=!0);null==d&&(d=0);this.mSequences.push(new e.tileSheet.AnimSeqData(a,b,d,t))},set_frame:function(a){this.curFrame=a;this.curIndex=null!=this.curAnim?this.curAnim.arFrames[this.curFrame]:a;this.dirty=!0;return a},initialize:function(a){null!=a&&(this.mAnimSheet=a,this.curAnim=null,this.set_frame(0),this.drawFrame(!0))},__class__:e.tileSheet.AnimSprite});e.tileSheet.AnimTextureSheet=function(){this.mTextureRegions=[];this.mFrameRect=new q.Rectangle;this.mFrameOffsets=
[]};e.tileSheet.AnimTextureSheet.__name__=!0;e.tileSheet.AnimTextureSheet.prototype={getFrameData:function(a){return this.arFrameData[a]},init:function(a){this.arFrameData=a;for(var b,d,e=0;e<a.length;)b=new q.Rectangle,b.x=a[e].x,b.y=a[e].y,b.width=a[e].w,b.height=a[e].h,this.mTextureRegions.push(b),d=new q.Point,d.x=a[e].offX,d.y=a[e].offY,this.mFrameOffsets.push(d),this.mFrameRect.width=Math.max(this.mFrameRect.width,b.width+d.x),this.mFrameRect.height=Math.max(this.mFrameRect.height,b.height+
d.y),e++},get_frameHeight:function(a){return this.mTextureRegions[a].height+this.mFrameOffsets[a].y},get_frameWidth:function(a){return this.mTextureRegions[a].width+this.mFrameOffsets[a].x},__class__:e.tileSheet.AnimTextureSheet};e.tileSheet.TileSheetHelper=function(){};e.tileSheet.TileSheetHelper.__name__=!0;e.tileSheet.TileSheetHelper.__super__=u;e.tileSheet.TileSheetHelper.prototype=v(u.prototype,{populateFrameArray:function(a,b){for(var d,e,i,f=0,g=A.fields(b);f<g.length;)d=g[f],++f,e=d.substring(0,
d.lastIndexOf(".png")),d=A.field(b,d),i=d.frame,i.id=e,i.offX=0,i.offY=0,d.trimmed&&(i.offX=d.spriteSourceSize.x,i.offY=d.spriteSourceSize.y),a.push(i)},onShort:function(a,b){var d=a.id.toLowerCase(),e=b.id.toLowerCase();return d<e?-1:d>e?1:0},prepareAnimTexture:function(a){var b=y.parse(a),a=[];this.populateFrameArray(a,b.frames);a.sort(C(this,this.onShort));b=new e.tileSheet.AnimTextureSheet;b.init(a);return b},get_name:function(){return"TileSheetHelper_2"},__class__:e.tileSheet.TileSheetHelper});
a={Key:{__ename__:!0,__constructs__:"A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,Number0,Number1,Number2,Number3,Number4,Number5,Number6,Number7,Number8,Number9,Numpad0,Numpad1,Numpad2,Numpad3,Numpad4,Numpad5,Numpad6,Numpad7,Numpad8,Numpad9,NumpadAdd,NumpadDecimal,NumpadDivide,NumpadEnter,NumpadMultiply,NumpadSubtract,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,Left,Up,Right,Down,Alt,Backquote,Backslash,Backspace,CapsLock,Comma,Command,Control,Delete,End,Enter,Equals,Escape,Home,Insert,LeftBracket,Minus,PageDown,PageUp,Period,Quote,RightBracket,Semicolon,Shift,Slash,Space,Tab,Menu,Search,Unknown".split(",")}};
a.Key.A=["A",0];a.Key.A.toString=f;a.Key.A.__enum__=a.Key;a.Key.B=["B",1];a.Key.B.toString=f;a.Key.B.__enum__=a.Key;a.Key.C=["C",2];a.Key.C.toString=f;a.Key.C.__enum__=a.Key;a.Key.D=["D",3];a.Key.D.toString=f;a.Key.D.__enum__=a.Key;a.Key.E=["E",4];a.Key.E.toString=f;a.Key.E.__enum__=a.Key;a.Key.F=["F",5];a.Key.F.toString=f;a.Key.F.__enum__=a.Key;a.Key.G=["G",6];a.Key.G.toString=f;a.Key.G.__enum__=a.Key;a.Key.H=["H",7];a.Key.H.toString=f;a.Key.H.__enum__=a.Key;a.Key.I=["I",8];a.Key.I.toString=f;a.Key.I.__enum__=
a.Key;a.Key.J=["J",9];a.Key.J.toString=f;a.Key.J.__enum__=a.Key;a.Key.K=["K",10];a.Key.K.toString=f;a.Key.K.__enum__=a.Key;a.Key.L=["L",11];a.Key.L.toString=f;a.Key.L.__enum__=a.Key;a.Key.M=["M",12];a.Key.M.toString=f;a.Key.M.__enum__=a.Key;a.Key.N=["N",13];a.Key.N.toString=f;a.Key.N.__enum__=a.Key;a.Key.O=["O",14];a.Key.O.toString=f;a.Key.O.__enum__=a.Key;a.Key.P=["P",15];a.Key.P.toString=f;a.Key.P.__enum__=a.Key;a.Key.Q=["Q",16];a.Key.Q.toString=f;a.Key.Q.__enum__=a.Key;a.Key.R=["R",17];a.Key.R.toString=
f;a.Key.R.__enum__=a.Key;a.Key.S=["S",18];a.Key.S.toString=f;a.Key.S.__enum__=a.Key;a.Key.T=["T",19];a.Key.T.toString=f;a.Key.T.__enum__=a.Key;a.Key.U=["U",20];a.Key.U.toString=f;a.Key.U.__enum__=a.Key;a.Key.V=["V",21];a.Key.V.toString=f;a.Key.V.__enum__=a.Key;a.Key.W=["W",22];a.Key.W.toString=f;a.Key.W.__enum__=a.Key;a.Key.X=["X",23];a.Key.X.toString=f;a.Key.X.__enum__=a.Key;a.Key.Y=["Y",24];a.Key.Y.toString=f;a.Key.Y.__enum__=a.Key;a.Key.Z=["Z",25];a.Key.Z.toString=f;a.Key.Z.__enum__=a.Key;a.Key.Number0=
["Number0",26];a.Key.Number0.toString=f;a.Key.Number0.__enum__=a.Key;a.Key.Number1=["Number1",27];a.Key.Number1.toString=f;a.Key.Number1.__enum__=a.Key;a.Key.Number2=["Number2",28];a.Key.Number2.toString=f;a.Key.Number2.__enum__=a.Key;a.Key.Number3=["Number3",29];a.Key.Number3.toString=f;a.Key.Number3.__enum__=a.Key;a.Key.Number4=["Number4",30];a.Key.Number4.toString=f;a.Key.Number4.__enum__=a.Key;a.Key.Number5=["Number5",31];a.Key.Number5.toString=f;a.Key.Number5.__enum__=a.Key;a.Key.Number6=["Number6",
32];a.Key.Number6.toString=f;a.Key.Number6.__enum__=a.Key;a.Key.Number7=["Number7",33];a.Key.Number7.toString=f;a.Key.Number7.__enum__=a.Key;a.Key.Number8=["Number8",34];a.Key.Number8.toString=f;a.Key.Number8.__enum__=a.Key;a.Key.Number9=["Number9",35];a.Key.Number9.toString=f;a.Key.Number9.__enum__=a.Key;a.Key.Numpad0=["Numpad0",36];a.Key.Numpad0.toString=f;a.Key.Numpad0.__enum__=a.Key;a.Key.Numpad1=["Numpad1",37];a.Key.Numpad1.toString=f;a.Key.Numpad1.__enum__=a.Key;a.Key.Numpad2=["Numpad2",38];
a.Key.Numpad2.toString=f;a.Key.Numpad2.__enum__=a.Key;a.Key.Numpad3=["Numpad3",39];a.Key.Numpad3.toString=f;a.Key.Numpad3.__enum__=a.Key;a.Key.Numpad4=["Numpad4",40];a.Key.Numpad4.toString=f;a.Key.Numpad4.__enum__=a.Key;a.Key.Numpad5=["Numpad5",41];a.Key.Numpad5.toString=f;a.Key.Numpad5.__enum__=a.Key;a.Key.Numpad6=["Numpad6",42];a.Key.Numpad6.toString=f;a.Key.Numpad6.__enum__=a.Key;a.Key.Numpad7=["Numpad7",43];a.Key.Numpad7.toString=f;a.Key.Numpad7.__enum__=a.Key;a.Key.Numpad8=["Numpad8",44];a.Key.Numpad8.toString=
f;a.Key.Numpad8.__enum__=a.Key;a.Key.Numpad9=["Numpad9",45];a.Key.Numpad9.toString=f;a.Key.Numpad9.__enum__=a.Key;a.Key.NumpadAdd=["NumpadAdd",46];a.Key.NumpadAdd.toString=f;a.Key.NumpadAdd.__enum__=a.Key;a.Key.NumpadDecimal=["NumpadDecimal",47];a.Key.NumpadDecimal.toString=f;a.Key.NumpadDecimal.__enum__=a.Key;a.Key.NumpadDivide=["NumpadDivide",48];a.Key.NumpadDivide.toString=f;a.Key.NumpadDivide.__enum__=a.Key;a.Key.NumpadEnter=["NumpadEnter",49];a.Key.NumpadEnter.toString=f;a.Key.NumpadEnter.__enum__=
a.Key;a.Key.NumpadMultiply=["NumpadMultiply",50];a.Key.NumpadMultiply.toString=f;a.Key.NumpadMultiply.__enum__=a.Key;a.Key.NumpadSubtract=["NumpadSubtract",51];a.Key.NumpadSubtract.toString=f;a.Key.NumpadSubtract.__enum__=a.Key;a.Key.F1=["F1",52];a.Key.F1.toString=f;a.Key.F1.__enum__=a.Key;a.Key.F2=["F2",53];a.Key.F2.toString=f;a.Key.F2.__enum__=a.Key;a.Key.F3=["F3",54];a.Key.F3.toString=f;a.Key.F3.__enum__=a.Key;a.Key.F4=["F4",55];a.Key.F4.toString=f;a.Key.F4.__enum__=a.Key;a.Key.F5=["F5",56];a.Key.F5.toString=
f;a.Key.F5.__enum__=a.Key;a.Key.F6=["F6",57];a.Key.F6.toString=f;a.Key.F6.__enum__=a.Key;a.Key.F7=["F7",58];a.Key.F7.toString=f;a.Key.F7.__enum__=a.Key;a.Key.F8=["F8",59];a.Key.F8.toString=f;a.Key.F8.__enum__=a.Key;a.Key.F9=["F9",60];a.Key.F9.toString=f;a.Key.F9.__enum__=a.Key;a.Key.F10=["F10",61];a.Key.F10.toString=f;a.Key.F10.__enum__=a.Key;a.Key.F11=["F11",62];a.Key.F11.toString=f;a.Key.F11.__enum__=a.Key;a.Key.F12=["F12",63];a.Key.F12.toString=f;a.Key.F12.__enum__=a.Key;a.Key.F13=["F13",64];a.Key.F13.toString=
f;a.Key.F13.__enum__=a.Key;a.Key.F14=["F14",65];a.Key.F14.toString=f;a.Key.F14.__enum__=a.Key;a.Key.F15=["F15",66];a.Key.F15.toString=f;a.Key.F15.__enum__=a.Key;a.Key.Left=["Left",67];a.Key.Left.toString=f;a.Key.Left.__enum__=a.Key;a.Key.Up=["Up",68];a.Key.Up.toString=f;a.Key.Up.__enum__=a.Key;a.Key.Right=["Right",69];a.Key.Right.toString=f;a.Key.Right.__enum__=a.Key;a.Key.Down=["Down",70];a.Key.Down.toString=f;a.Key.Down.__enum__=a.Key;a.Key.Alt=["Alt",71];a.Key.Alt.toString=f;a.Key.Alt.__enum__=
a.Key;a.Key.Backquote=["Backquote",72];a.Key.Backquote.toString=f;a.Key.Backquote.__enum__=a.Key;a.Key.Backslash=["Backslash",73];a.Key.Backslash.toString=f;a.Key.Backslash.__enum__=a.Key;a.Key.Backspace=["Backspace",74];a.Key.Backspace.toString=f;a.Key.Backspace.__enum__=a.Key;a.Key.CapsLock=["CapsLock",75];a.Key.CapsLock.toString=f;a.Key.CapsLock.__enum__=a.Key;a.Key.Comma=["Comma",76];a.Key.Comma.toString=f;a.Key.Comma.__enum__=a.Key;a.Key.Command=["Command",77];a.Key.Command.toString=f;a.Key.Command.__enum__=
a.Key;a.Key.Control=["Control",78];a.Key.Control.toString=f;a.Key.Control.__enum__=a.Key;a.Key.Delete=["Delete",79];a.Key.Delete.toString=f;a.Key.Delete.__enum__=a.Key;a.Key.End=["End",80];a.Key.End.toString=f;a.Key.End.__enum__=a.Key;a.Key.Enter=["Enter",81];a.Key.Enter.toString=f;a.Key.Enter.__enum__=a.Key;a.Key.Equals=["Equals",82];a.Key.Equals.toString=f;a.Key.Equals.__enum__=a.Key;a.Key.Escape=["Escape",83];a.Key.Escape.toString=f;a.Key.Escape.__enum__=a.Key;a.Key.Home=["Home",84];a.Key.Home.toString=
f;a.Key.Home.__enum__=a.Key;a.Key.Insert=["Insert",85];a.Key.Insert.toString=f;a.Key.Insert.__enum__=a.Key;a.Key.LeftBracket=["LeftBracket",86];a.Key.LeftBracket.toString=f;a.Key.LeftBracket.__enum__=a.Key;a.Key.Minus=["Minus",87];a.Key.Minus.toString=f;a.Key.Minus.__enum__=a.Key;a.Key.PageDown=["PageDown",88];a.Key.PageDown.toString=f;a.Key.PageDown.__enum__=a.Key;a.Key.PageUp=["PageUp",89];a.Key.PageUp.toString=f;a.Key.PageUp.__enum__=a.Key;a.Key.Period=["Period",90];a.Key.Period.toString=f;a.Key.Period.__enum__=
a.Key;a.Key.Quote=["Quote",91];a.Key.Quote.toString=f;a.Key.Quote.__enum__=a.Key;a.Key.RightBracket=["RightBracket",92];a.Key.RightBracket.toString=f;a.Key.RightBracket.__enum__=a.Key;a.Key.Semicolon=["Semicolon",93];a.Key.Semicolon.toString=f;a.Key.Semicolon.__enum__=a.Key;a.Key.Shift=["Shift",94];a.Key.Shift.toString=f;a.Key.Shift.__enum__=a.Key;a.Key.Slash=["Slash",95];a.Key.Slash.toString=f;a.Key.Slash.__enum__=a.Key;a.Key.Space=["Space",96];a.Key.Space.toString=f;a.Key.Space.__enum__=a.Key;a.Key.Tab=
["Tab",97];a.Key.Tab.toString=f;a.Key.Tab.__enum__=a.Key;a.Key.Menu=["Menu",98];a.Key.Menu.toString=f;a.Key.Menu.__enum__=a.Key;a.Key.Search=["Search",99];a.Key.Search.toString=f;a.Key.Search.__enum__=a.Key;a.Key.Unknown=function(c){c=["Unknown",100,c];c.__enum__=a.Key;c.toString=f;return c};a.Keyboard=function(){};a.Keyboard.__name__=!0;a.KeyboardEvent=function(){this.init(0,null)};a.KeyboardEvent.__name__=!0;a.KeyboardEvent.prototype={init:function(a,b){this.id=a;this.key=b},__class__:a.KeyboardEvent};
a.Mouse=function(){};a.Mouse.__name__=!0;a.MouseButton={__ename__:!0,__constructs__:["Left","Middle","Right","Unknown"]};a.MouseButton.Left=["Left",0];a.MouseButton.Left.toString=f;a.MouseButton.Left.__enum__=a.MouseButton;a.MouseButton.Middle=["Middle",1];a.MouseButton.Middle.toString=f;a.MouseButton.Middle.__enum__=a.MouseButton;a.MouseButton.Right=["Right",2];a.MouseButton.Right.toString=f;a.MouseButton.Right.__enum__=a.MouseButton;a.MouseButton.Unknown=function(c){c=["Unknown",3,c];c.__enum__=
a.MouseButton;c.toString=f;return c};a.MouseCursor={__ename__:!0,__constructs__:["Default","Button","None"]};a.MouseCursor.Default=["Default",0];a.MouseCursor.Default.toString=f;a.MouseCursor.Default.__enum__=a.MouseCursor;a.MouseCursor.Button=["Button",1];a.MouseCursor.Button.toString=f;a.MouseCursor.Button.__enum__=a.MouseCursor;a.MouseCursor.None=["None",2];a.MouseCursor.None.toString=f;a.MouseCursor.None.__enum__=a.MouseCursor;a.MouseEvent=function(){this.init(0,0,0,null)};a.MouseEvent.__name__=
!0;a.MouseEvent.prototype={init:function(a,b,d,e){this.id=a;this.viewX=b;this.viewY=d;this.button=e},__class__:a.MouseEvent};a.Pointer=function(){};a.Pointer.__name__=!0;a.EventSource={__ename__:!0,__constructs__:["Mouse","Touch"]};a.EventSource.Mouse=function(c){c=["Mouse",0,c];c.__enum__=a.EventSource;c.toString=f;return c};a.EventSource.Touch=function(c){c=["Touch",1,c];c.__enum__=a.EventSource;c.toString=f;return c};a.PointerEvent=function(){this.init(0,0,0,null,null)};a.PointerEvent.__name__=
!0;a.PointerEvent.prototype={init:function(a,b,d,e,i){this.id=a;this.viewX=b;this.viewY=d;this.hit=e;this.source=i;this._stopped=!1},__class__:a.PointerEvent};a.Touch=function(){};a.Touch.__name__=!0;a.TouchPoint=function(c){this.id=c;this._source=a.EventSource.Touch(this)};a.TouchPoint.__name__=!0;a.TouchPoint.prototype={init:function(a,b){this.viewX=a;this.viewY=b},__class__:a.TouchPoint};q.FMath=function(){};q.FMath.__name__=!0;q.FMath.max=function(a,b){return a>b?a:b};q.Matrix=function(){this.identity()};
q.Matrix.__name__=!0;q.Matrix.prototype={inverseTransform:function(a,b,d){var e=this.determinant();if(0==e)return!1;a-=this.m02;b-=this.m12;d.x=(a*this.m11-b*this.m01)/e;d.y=(b*this.m00-a*this.m10)/e;return!0},determinant:function(){return this.m00*this.m11-this.m01*this.m10},translate:function(a,b){this.m02+=this.m00*a+this.m01*b;this.m12+=this.m11*b+this.m10*a},compose:function(a,b,d,e,i){var f=Math.sin(i),i=Math.cos(i);this.set(i*d,f*d,-f*e,i*e,a,b)},identity:function(){this.set(1,0,0,1,0,0)},
set:function(a,b,d,e,i,f){this.m00=a;this.m01=d;this.m02=i;this.m10=b;this.m11=e;this.m12=f},__class__:q.Matrix};q.Rectangle=function(a,b,d,e){null==e&&(e=0);null==d&&(d=0);null==b&&(b=0);null==a&&(a=0);this.set(a,b,d,e)};q.Rectangle.__name__=!0;q.Rectangle.prototype={contains:function(a,b){a-=this.x;b-=this.y;return 0<=a&&0<=b&&a<=this.width&&b<=this.height},set:function(a,b,d,e){this.x=a;this.y=b;this.width=d;this.height=e},__class__:q.Rectangle};b.BasicAssetPackLoader=function(a,j){var d=this;
this._platform=a;this.promise=new h.Promise;this._bytesLoaded=new n.StringMap;this._pack=new b._BasicAssetPackLoader.BasicAssetPack(j);var e=D.array(j);if(0==e.length)this.handleSuccess();else{for(var i=new n.StringMap,f=0;f<e.length;){var g=e[f];++f;var k=i.get(g.name);null==k&&(k=[],i.set(g.name,k));k.push(g)}this._assetsRemaining=D.count(i);for(e=function(){return function(a){return function(){return function(){return a.iterator()}}()}}()(i)();e.hasNext();)k=e.next(),k=[k],this.pickBestEntry(k[0],
function(a){return function(c){if(null!=c){var e=j.getFullURL(c);try{d.loadEntry(e,c)}catch(i){d.handleError(c,"Unexpected error: "+w.string(i))}e=d.promise;e.set_total(e._total+c.bytes)}else c=a[0][0],b.BasicAssetPackLoader.isAudio(c.format)?d.handleLoad(c,b.DummySound.getInstance()):d.handleError(c,"Could not find a supported format to load")}}(k))}};b.BasicAssetPackLoader.__name__=!0;b.BasicAssetPackLoader.isAudio=function(a){switch(a[1]){case 5:case 6:case 7:case 8:return!0;default:return!1}};
b.BasicAssetPackLoader.prototype={handleTextureError:function(a){this.handleError(a,"Failed to create texture. Is the GPU context unavailable?")},handleError:function(a,b){this.promise.error.emit1(h.Strings.withFields(b,["url",a.url]))},handleSuccess:function(){this.promise.set_result(this._pack)},handleProgress:function(a,b){this._bytesLoaded.set(a.name,b);for(var d=0,e=function(a){return function(){return a.iterator()}}(this._bytesLoaded)();e.hasNext();)var i=e.next(),d=d+i;this.promise.set_progress(d)},
handleLoad:function(a,b){this.handleProgress(a,a.bytes);var d=a.name;switch(a.format[1]){case 0:case 1:case 2:case 3:case 4:this._pack.textures.set(d,b);break;case 5:case 6:case 7:case 8:this._pack.sounds.set(d,b);break;case 9:this._pack.files.set(d,b)}this._assetsRemaining-=1;0>=this._assetsRemaining&&this.handleSuccess()},getAssetFormats:function(){null},loadEntry:function(){null},pickBestEntry:function(a,b){this.getAssetFormats(function(d){for(var e=0;e<d.length;){var i=d[e];++e;for(var f=0;f<
a.length;){var g=a[f];++f;if(g.format==i){b(g);return}}}b(null)})},__class__:b.BasicAssetPackLoader};b._BasicAssetPackLoader={};b._BasicAssetPackLoader.BasicAssetPack=function(a){this._manifest=a;this.textures=new n.StringMap;this.sounds=new n.StringMap;this.files=new n.StringMap};b._BasicAssetPackLoader.BasicAssetPack.__name__=!0;b._BasicAssetPackLoader.BasicAssetPack.__interfaces__=[g.AssetPack];b._BasicAssetPackLoader.BasicAssetPack.prototype={getFile:function(a,b){null==b&&(b=!0);var d=this.files.get(a);
if(null==d&&b)throw h.Strings.withFields("Missing file",["name",a]);return d},getTexture:function(a,b){null==b&&(b=!0);var d=this.textures.get(a);if(null==d&&b)throw h.Strings.withFields("Missing texture",["name",a]);return d},__class__:b._BasicAssetPackLoader.BasicAssetPack};b.BasicKeyboard=function(){this.down=new h.Signal1;this.up=new h.Signal1;this.backButton=new h.Signal0;this._keyStates=new n.IntMap};b.BasicKeyboard.__name__=!0;b.BasicKeyboard.__interfaces__=[a.Keyboard];b.BasicKeyboard.prototype=
{submitUp:function(a){this._keyStates.exists(a)&&(this._keyStates.remove(a),b.BasicKeyboard._sharedEvent.init(b.BasicKeyboard._sharedEvent.id+1,b.KeyCodes.toKey(a)),this.up.emit1(b.BasicKeyboard._sharedEvent))},submitDown:function(a){if(16777238==a)return null!=this.backButton._head?(this.backButton.emit0(),!0):!1;this._keyStates.exists(a)||(this._keyStates.set(a,!0),b.BasicKeyboard._sharedEvent.init(b.BasicKeyboard._sharedEvent.id+1,b.KeyCodes.toKey(a)),this.down.emit1(b.BasicKeyboard._sharedEvent));
return!0},__class__:b.BasicKeyboard};b.BasicMouse=function(c){this._pointer=c;this._source=a.EventSource.Mouse(b.BasicMouse._sharedEvent);this.down=new h.Signal1;this.move=new h.Signal1;this.up=new h.Signal1;this.scroll=new h.Signal1;this._y=this._x=0;this._cursor=a.MouseCursor.Default;this._buttonStates=new n.IntMap};b.BasicMouse.__name__=!0;b.BasicMouse.__interfaces__=[a.Mouse];b.BasicMouse.prototype={prepare:function(a,j,d){this._x=a;this._y=j;b.BasicMouse._sharedEvent.init(b.BasicMouse._sharedEvent.id+
1,a,j,d)},submitScroll:function(a,b,d){this._x=a;this._y=b;if(null==this.scroll._head)return!1;this.scroll.emit1(d);return!0},submitUp:function(a,j,d){this._buttonStates.exists(d)&&(this._buttonStates.remove(d),this.prepare(a,j,b.MouseCodes.toButton(d)),this._pointer.submitUp(a,j,this._source),this.up.emit1(b.BasicMouse._sharedEvent))},submitMove:function(a,j){this.prepare(a,j,null);this._pointer.submitMove(a,j,this._source);this.move.emit1(b.BasicMouse._sharedEvent)},submitDown:function(a,j,d){this._buttonStates.exists(d)||
(this._buttonStates.set(d,!0),this.prepare(a,j,b.MouseCodes.toButton(d)),this._pointer.submitDown(a,j,this._source),this.down.emit1(b.BasicMouse._sharedEvent))},__class__:b.BasicMouse};b.BasicPointer=function(a,b,d){null==d&&(d=!1);null==b&&(b=0);null==a&&(a=0);this.down=new h.Signal1;this.move=new h.Signal1;this.up=new h.Signal1;this._x=a;this._y=b;this._isDown=d};b.BasicPointer.__name__=!0;b.BasicPointer.__interfaces__=[a.Pointer];b.BasicPointer.prototype={prepare:function(a,j,d,e){this._x=a;this._y=
j;b.BasicPointer._sharedEvent.init(b.BasicPointer._sharedEvent.id+1,a,j,d,e)},submitUp:function(a,j,d){if(this._isDown){this._isDown=!1;var f=[],i=e.Sprite.hitTest(m.root,a,j);if(null!=i){var g=i.owner;do{var h=g._compMap.Sprite_1;null!=h&&f.push(h);g=g.parent}while(null!=g)}this.prepare(a,j,i,d);for(a=0;a<f.length;)if(h=f[a],++a,h=h._pointerUp,null!=h&&(h.emit1(b.BasicPointer._sharedEvent),b.BasicPointer._sharedEvent._stopped))return;this.up.emit1(b.BasicPointer._sharedEvent)}},submitMove:function(a,
j,d){var f=[],i=e.Sprite.hitTest(m.root,a,j);if(null!=i){var g=i.owner;do{var h=g._compMap.Sprite_1;null!=h&&f.push(h);g=g.parent}while(null!=g)}this.prepare(a,j,i,d);for(a=0;a<f.length;)if(h=f[a],++a,h=h._pointerMove,null!=h&&(h.emit1(b.BasicPointer._sharedEvent),b.BasicPointer._sharedEvent._stopped))return;this.move.emit1(b.BasicPointer._sharedEvent)},submitDown:function(a,j,d){if(!this._isDown){this._isDown=!0;var f=[],i=e.Sprite.hitTest(m.root,a,j);if(null!=i){var g=i.owner;do{var h=g._compMap.Sprite_1;
null!=h&&f.push(h);g=g.parent}while(null!=g)}this.prepare(a,j,i,d);for(a=0;a<f.length;)if(h=f[a],++a,h=h._pointerDown,null!=h&&(h.emit1(b.BasicPointer._sharedEvent),b.BasicPointer._sharedEvent._stopped))return;this.down.emit1(b.BasicPointer._sharedEvent)}},__class__:b.BasicPointer};b.BasicTouch=function(a,b){null==b&&(b=4);this._pointer=a;this._maxPoints=b;this._pointMap=new n.IntMap;this._points=[];this.down=new h.Signal1;this.move=new h.Signal1;this.up=new h.Signal1};b.BasicTouch.__name__=!0;b.BasicTouch.__interfaces__=
[a.Touch];b.BasicTouch.prototype={submitUp:function(a,b,d){var e=this._pointMap.get(a);null!=e&&(e.init(b,d),this._pointMap.remove(a),o.remove(this._points,e),this._pointerTouch==e&&(this._pointerTouch=null,this._pointer.submitUp(b,d,e._source)),this.up.emit1(e))},submitMove:function(a,b,d){a=this._pointMap.get(a);null!=a&&(a.init(b,d),this._pointerTouch==a&&this._pointer.submitMove(b,d,a._source),this.move.emit1(a))},submitDown:function(c,b,d){if(!this._pointMap.exists(c)){var e=new a.TouchPoint(c);
e.init(b,d);this._pointMap.set(c,e);this._points.push(e);null==this._pointerTouch&&(this._pointerTouch=e,this._pointer.submitDown(b,d,e._source));this.down.emit1(e)}},__class__:b.BasicTouch};l={Sound:function(){}};l.Sound.__name__=!0;b.DummySound=function(){this._playback=new b.DummyPlayback(this)};b.DummySound.__name__=!0;b.DummySound.__interfaces__=[l.Sound];b.DummySound.getInstance=function(){null==b.DummySound._instance&&(b.DummySound._instance=new b.DummySound);return b.DummySound._instance};
b.DummySound.prototype={__class__:b.DummySound};l.Playback=function(){};l.Playback.__name__=!0;l.Playback.__interfaces__=[h.Disposable];b.DummyPlayback=function(a){this._sound=a;this.volume=new p.AnimatedFloat(0)};b.DummyPlayback.__name__=!0;b.DummyPlayback.__interfaces__=[l.Playback];b.DummyPlayback.prototype={__class__:b.DummyPlayback};b.DummyTouch=function(){this.down=new h.Signal1;this.move=new h.Signal1;this.up=new h.Signal1};b.DummyTouch.__name__=!0;b.DummyTouch.__interfaces__=[a.Touch];b.DummyTouch.prototype=
{__class__:b.DummyTouch};b.EventGroup=function(){this._entries=[]};b.EventGroup.__name__=!0;b.EventGroup.__interfaces__=[h.Disposable];b.EventGroup.prototype={dispose:function(){for(var a=0,b=this._entries;a<b.length;){var d=b[a];++a;d.dispatcher.removeEventListener(d.type,d.listener,!1)}this._entries=[]},addDisposingListener:function(a,b,d){var e=this;this.addListener(a,b,function(a){e.dispose();d(a)})},addListener:function(a,j,d){a.addEventListener(j,d,!1);this._entries.push(new b._EventGroup.Entry(a,
j,d))},__class__:b.EventGroup};b._EventGroup={};b._EventGroup.Entry=function(a,b,d){this.dispatcher=a;this.type=b;this.listener=d};b._EventGroup.Entry.__name__=!0;b._EventGroup.Entry.prototype={__class__:b._EventGroup.Entry};b.KeyCodes=function(){};b.KeyCodes.__name__=!0;b.KeyCodes.toKey=function(c){switch(c){case 65:return a.Key.A;case 66:return a.Key.B;case 67:return a.Key.C;case 68:return a.Key.D;case 69:return a.Key.E;case 70:return a.Key.F;case 71:return a.Key.G;case 72:return a.Key.H;case 73:return a.Key.I;
case 74:return a.Key.J;case 75:return a.Key.K;case 76:return a.Key.L;case 77:return a.Key.M;case 78:return a.Key.N;case 79:return a.Key.O;case 80:return a.Key.P;case 81:return a.Key.Q;case 82:return a.Key.R;case 83:return a.Key.S;case 84:return a.Key.T;case 85:return a.Key.U;case 86:return a.Key.V;case 87:return a.Key.W;case 88:return a.Key.X;case 89:return a.Key.Y;case 90:return a.Key.Z;case 48:return a.Key.Number0;case 49:return a.Key.Number1;case 50:return a.Key.Number2;case 51:return a.Key.Number3;
case 52:return a.Key.Number4;case 53:return a.Key.Number5;case 54:return a.Key.Number6;case 55:return a.Key.Number7;case 56:return a.Key.Number8;case 57:return a.Key.Number9;case 96:return a.Key.Numpad0;case 97:return a.Key.Numpad1;case 98:return a.Key.Numpad2;case 99:return a.Key.Numpad3;case 100:return a.Key.Numpad4;case 101:return a.Key.Numpad5;case 102:return a.Key.Numpad6;case 103:return a.Key.Numpad7;case 104:return a.Key.Numpad8;case 105:return a.Key.Numpad9;case 107:return a.Key.NumpadAdd;
case 110:return a.Key.NumpadDecimal;case 111:return a.Key.NumpadDivide;case 108:return a.Key.NumpadEnter;case 106:return a.Key.NumpadMultiply;case 109:return a.Key.NumpadSubtract;case 112:return a.Key.F1;case 113:return a.Key.F2;case 114:return a.Key.F3;case 115:return a.Key.F4;case 116:return a.Key.F5;case 117:return a.Key.F6;case 118:return a.Key.F7;case 119:return a.Key.F8;case 120:return a.Key.F9;case 121:return a.Key.F10;case 122:return a.Key.F11;case 123:return a.Key.F12;case 37:return a.Key.Left;
case 38:return a.Key.Up;case 39:return a.Key.Right;case 40:return a.Key.Down;case 18:return a.Key.Alt;case 192:return a.Key.Backquote;case 220:return a.Key.Backslash;case 8:return a.Key.Backspace;case 20:return a.Key.CapsLock;case 188:return a.Key.Comma;case 15:return a.Key.Command;case 17:return a.Key.Control;case 46:return a.Key.Delete;case 35:return a.Key.End;case 13:return a.Key.Enter;case 187:return a.Key.Equals;case 27:return a.Key.Escape;case 36:return a.Key.Home;case 45:return a.Key.Insert;
case 219:return a.Key.LeftBracket;case 189:return a.Key.Minus;case 34:return a.Key.PageDown;case 33:return a.Key.PageUp;case 190:return a.Key.Period;case 222:return a.Key.Quote;case 221:return a.Key.RightBracket;case 186:return a.Key.Semicolon;case 16:return a.Key.Shift;case 191:return a.Key.Slash;case 32:return a.Key.Space;case 9:return a.Key.Tab;case 16777234:return a.Key.Menu;case 16777247:return a.Key.Search}return a.Key.Unknown(c)};b.MainLoop=function(){this._tickables=[]};b.MainLoop.__name__=
!0;b.MainLoop.updateEntity=function(a,j){var d=a._compMap.SpeedAdjuster_5;if(null!=d&&(d._realDt=j,j*=d.scale._value,0>=j)){d.onUpdate(j);return}for(var e=a.firstComponent;null!=e;)d=e.next,e.onUpdate(j),e=d;for(e=a.firstChild;null!=e;)d=e.next,b.MainLoop.updateEntity(e,j),e=d};b.MainLoop.prototype={render:function(a){var b=a.willRender();null!=b&&(e.Sprite.render(m.root,b),a.didRender())},update:function(a){if(!(0>=a)){1<a&&(a=1);for(var j=0;j<this._tickables.length;){var d=this._tickables[j];null==
d||d.update(a)?this._tickables.splice(j,1):++j}m.volume.update(a);b.MainLoop.updateEntity(m.root,a)}},__class__:b.MainLoop};b.MouseCodes=function(){};b.MouseCodes.__name__=!0;b.MouseCodes.toButton=function(c){switch(c){case 0:return a.MouseButton.Left;case 1:return a.MouseButton.Middle;case 2:return a.MouseButton.Right}return a.MouseButton.Unknown(c)};b.Renderer=function(){};b.Renderer.__name__=!0;b.Renderer.prototype={__class__:b.Renderer};b.Tickable=function(){};b.Tickable.__name__=!0;b.Tickable.prototype=
{__class__:b.Tickable};b.html.CanvasGraphics=function(a){this._firstDraw=!1;this._canvasCtx=a.getContext("2d")};b.html.CanvasGraphics.__name__=!0;b.html.CanvasGraphics.__interfaces__=[e.Graphics];b.html.CanvasGraphics.prototype={willRender:function(){this._firstDraw=!0},applyScissor:function(a,b,d,e){this._canvasCtx.beginPath();this._canvasCtx.rect(a|0,b|0,d|0,e|0);this._canvasCtx.clip()},setBlendMode:function(a){var b;switch(a[1]){case 0:b="source-over";break;case 1:b="lighter";break;case 2:b="source-over"}this._canvasCtx.globalCompositeOperation=
b},multiplyAlpha:function(a){this._canvasCtx.globalAlpha*=a},fillRect:function(a,b,d,e,i){this._firstDraw?(this._firstDraw=!1,this._canvasCtx.globalCompositeOperation="copy",this.fillRect(a,b,d,e,i),this._canvasCtx.globalCompositeOperation="source-over"):(this._canvasCtx.fillStyle="#"+("00000"+a.toString(16)).slice(-6),this._canvasCtx.fillRect(b|0,d|0,e|0,i|0))},drawSubImage:function(a,b,d,e,i,f,g){this._firstDraw?(this._firstDraw=!1,this._canvasCtx.globalCompositeOperation="copy",this.drawSubImage(a,
b,d,e,i,f,g),this._canvasCtx.globalCompositeOperation="source-over"):this._canvasCtx.drawImage(a.image,e|0,i|0,f|0,g|0,b|0,d|0,f|0,g|0)},restore:function(){this._canvasCtx.restore()},transform:function(a,b,d,e,f,g){this._canvasCtx.transform(a,b,d,e,f|0,g|0)},save:function(){this._canvasCtx.save()},__class__:b.html.CanvasGraphics};b.html.CanvasRenderer=function(a){this._graphics=new b.html.CanvasGraphics(a)};b.html.CanvasRenderer.__name__=!0;b.html.CanvasRenderer.__interfaces__=[b.Renderer];b.html.CanvasRenderer.prototype=
{didRender:function(){},willRender:function(){this._graphics.willRender();return this._graphics},createTexture:function(a){return new b.html.CanvasTexture(b.html.CanvasRenderer.CANVAS_TEXTURES?b.html.HtmlUtil.createCanvas(a):a)},__class__:b.html.CanvasRenderer};b.html.CanvasTexture=function(a){this.image=a};b.html.CanvasTexture.__name__=!0;b.html.CanvasTexture.__interfaces__=[e.Texture];b.html.CanvasTexture.prototype={__class__:b.html.CanvasTexture};b.html.HtmlAssetPackLoader=function(a,e){b.BasicAssetPackLoader.call(this,
a,e)};b.html.HtmlAssetPackLoader.__name__=!0;b.html.HtmlAssetPackLoader.detectImageFormats=function(a){var b=[g.AssetFormat.PNG,g.AssetFormat.JPG,g.AssetFormat.GIF],d=2,e=k.document.createElement("img");e.onload=e.onerror=function(){1==e.width&&b.unshift(g.AssetFormat.WEBP);--d;0==d&&a(b)};e.src="data:image/webp;base64,UklGRhoAAABXRUJQVlA4TA0AAAAvAAAAEAcQERGIiP4HAA==";var f=k.document.createElement("img");f.onload=f.onerror=function(){1==f.width&&b.unshift(g.AssetFormat.JXR);--d;0==d&&a(b)};f.src=
"data:image/vnd.ms-photo;base64,SUm8AQgAAAAFAAG8AQAQAAAASgAAAIC8BAABAAAAAQAAAIG8BAABAAAAAQAAAMC8BAABAAAAWgAAAMG8BAABAAAAHwAAAAAAAAAkw91vA07+S7GFPXd2jckNV01QSE9UTwAZAYBxAAAAABP/gAAEb/8AAQAAAQAAAA=="};b.html.HtmlAssetPackLoader.detectAudioFormats=function(){var a=k.document.createElement("audio");if(null==a||null==C(a,a.canPlayType))return[];var e=new z("\\b(iPhone|iPod|iPad|Android)\\b",""),d=k.window.navigator.userAgent;if(!b.html.WebAudioSound.get_supported()&&e.match(d))return[];for(var e=[{format:g.AssetFormat.M4A,
mimeType:"audio/mp4; codecs=mp4a"},{format:g.AssetFormat.MP3,mimeType:"audio/mpeg"},{format:g.AssetFormat.OGG,mimeType:"audio/ogg; codecs=vorbis"},{format:g.AssetFormat.WAV,mimeType:"audio/wav"}],d=[],f=0;f<e.length;){var i=e[f];++f;var h="";try{h=a.canPlayType(i.mimeType)}catch(l){}""!=h&&d.push(i.format)}return d};b.html.HtmlAssetPackLoader.supportsBlob=function(){if(b.html.HtmlAssetPackLoader._detectBlobSupport){b.html.HtmlAssetPackLoader._detectBlobSupport=!1;var a=new XMLHttpRequest;a.open("GET",
".",!0);a.responseType="blob";if("blob"!=a.responseType)return!1;b.html.HtmlAssetPackLoader._URL=b.html.HtmlUtil.loadExtension("URL").value}return null!=b.html.HtmlAssetPackLoader._URL&&null!=b.html.HtmlAssetPackLoader._URL.createObjectURL};b.html.HtmlAssetPackLoader.__super__=b.BasicAssetPackLoader;b.html.HtmlAssetPackLoader.prototype=v(b.BasicAssetPackLoader.prototype,{sendRequest:function(a,b,d,e){var f=this,g=new XMLHttpRequest,h=0,l=function(){h=Date.now();g.open("GET",a,!0);g.responseType=d;
""==g.responseType&&(g.responseType="arraybuffer");g.send()},m=0;if("undefined"!=typeof g.onprogress){var n=4;g.onprogress=function(a){h=Date.now();f.handleProgress(b,a.loaded)};m=k.window.setInterval(function(){1<=g.readyState&&5E3<Date.now()-h&&(g.abort(),--n,0<n?l():(k.window.clearInterval(m),f.handleError(b,"Request timed out")))},1E3)}g.onload=function(){k.window.clearInterval(m);var a=g.response;null==a?a=g.responseText:"blob"==d&&"arraybuffer"==g.responseType&&(a=new Blob([g.response]));e(a)};
g.onerror=function(){k.window.clearInterval(m);f.handleError(b,"Failed to load asset: error #"+g.status)};l();return g},getAssetFormats:function(a){null==b.html.HtmlAssetPackLoader._supportedFormats&&(b.html.HtmlAssetPackLoader._supportedFormats=new h.Promise,b.html.HtmlAssetPackLoader.detectImageFormats(function(a){b.html.HtmlAssetPackLoader._supportedFormats.set_result(a.concat(b.html.HtmlAssetPackLoader.detectAudioFormats()).concat([g.AssetFormat.Data]))}));b.html.HtmlAssetPackLoader._supportedFormats.get(a)},
loadEntry:function(a,e){var d=this;switch(e.format[1]){case 0:case 1:case 2:case 3:case 4:var f=k.document.createElement("img"),g=new b.EventGroup;g.addDisposingListener(f,"load",function(){b.html.HtmlAssetPackLoader.supportsBlob()&&b.html.HtmlAssetPackLoader._URL.revokeObjectURL(f.src);var a=d._platform.getRenderer().createTexture(f);null!=a?d.handleLoad(e,a):d.handleTextureError(e)});g.addDisposingListener(f,"error",function(){d.handleError(e,"Failed to load image")});b.html.HtmlAssetPackLoader.supportsBlob()?
this.sendRequest(a,e,"blob",function(a){f.src=b.html.HtmlAssetPackLoader._URL.createObjectURL(a)}):f.src=a;break;case 5:case 6:case 7:case 8:if(b.html.WebAudioSound.get_supported())this.sendRequest(a,e,"arraybuffer",function(a){b.html.WebAudioSound.ctx.decodeAudioData(a,function(a){d.handleLoad(e,new b.html.WebAudioSound(a))},function(){d.handleLoad(e,b.DummySound.getInstance())})});else{var h=k.document.createElement("audio");h.preload="auto";var l=++b.html.HtmlAssetPackLoader._mediaRefCount;null==
b.html.HtmlAssetPackLoader._mediaElements&&(b.html.HtmlAssetPackLoader._mediaElements=new n.IntMap);b.html.HtmlAssetPackLoader._mediaElements.set(l,h);g=new b.EventGroup;g.addDisposingListener(h,"canplaythrough",function(){b.html.HtmlAssetPackLoader._mediaElements.remove(l);d.handleLoad(e,new b.html.HtmlSound(h))});g.addDisposingListener(h,"error",function(){b.html.HtmlAssetPackLoader._mediaElements.remove(l);var a=h.error.code;3==a||4==a?d.handleLoad(e,b.DummySound.getInstance()):d.handleError(e,
"Failed to load audio: "+h.error.code)});g.addListener(h,"progress",function(){if(0<h.buffered.length&&0<h.duration){var a=h.buffered.end(0)/h.duration;d.handleProgress(e,a*e.bytes|0)}});h.src=a;h.load()}break;case 9:this.sendRequest(a,e,"text",function(a){d.handleLoad(e,a)})}},__class__:b.html.HtmlAssetPackLoader});b.html.HtmlMouse=function(a,e){b.BasicMouse.call(this,a);this._canvas=e};b.html.HtmlMouse.__name__=!0;b.html.HtmlMouse.__super__=b.BasicMouse;b.html.HtmlMouse.prototype=v(b.BasicMouse.prototype,
{__class__:b.html.HtmlMouse});b.html.HtmlSound=function(a){this.audioElement=a};b.html.HtmlSound.__name__=!0;b.html.HtmlSound.__interfaces__=[l.Sound];b.html.HtmlSound.prototype={__class__:b.html.HtmlSound};b.html.HtmlStage=function(a){var e=this;this._canvas=a;this.resize=new h.Signal0;this.scaleFactor=b.html.HtmlStage.computeScaleFactor();1!=this.scaleFactor&&(b.html.HtmlUtil.setVendorStyle(this._canvas,"transform-origin","top left"),b.html.HtmlUtil.setVendorStyle(this._canvas,"transform","scale("+
1/this.scaleFactor+")"));b.html.HtmlUtil.SHOULD_HIDE_MOBILE_BROWSER&&(k.window.addEventListener("orientationchange",function(){b.html.HtmlUtil.callLater(C(e,e.hideMobileBrowser),200)},!1),this.hideMobileBrowser());k.window.addEventListener("resize",C(this,this.onWindowResize),!1);this.onWindowResize(null);this.orientation=new h.Value(null);null!=k.window.orientation&&(k.window.addEventListener("orientationchange",C(this,this.onOrientationChange),!1),this.onOrientationChange(null));this.fullscreen=
new h.Value(!1);b.html.HtmlUtil.addVendorListener(k.document,"fullscreenchange",function(){e.updateFullscreen()},!1);this.updateFullscreen()};b.html.HtmlStage.__name__=!0;b.html.HtmlStage.__interfaces__=[e.Stage];b.html.HtmlStage.computeScaleFactor=function(){var a=k.window.devicePixelRatio;null==a&&(a=1);var e=k.document.createElement("canvas").getContext("2d"),e=b.html.HtmlUtil.loadExtension("backingStorePixelRatio",e).value;null==e&&(e=1);a/=e;e=k.window.screen.height;return 1024<a*k.window.screen.width||
1024<a*e?1:a};b.html.HtmlStage.prototype={updateFullscreen:function(){this.fullscreen.set__(!0==b.html.HtmlUtil.loadFirstExtension(["fullscreen","fullScreen","isFullScreen"],k.document).value)},onOrientationChange:function(){this.orientation.set__(b.html.HtmlUtil.orientation(k.window.orientation))},hideMobileBrowser:function(){var a=this,e=k.document.documentElement.style;e.height=k.window.innerHeight+100+"px";e.width=k.window.innerWidth+"px";e.overflow="visible";b.html.HtmlUtil.callLater(function(){b.html.HtmlUtil.hideMobileBrowser();
b.html.HtmlUtil.callLater(function(){e.height=k.window.innerHeight+"px";a.onWindowResize(null)},100)})},resizeCanvas:function(a,b){var d=this.scaleFactor*a,e=this.scaleFactor*b;if(this._canvas.width==d&&this._canvas.height==e)return!1;this._canvas.width=d|0;this._canvas.height=e|0;this.resize.emit0();return!0},onWindowResize:function(){var a=this._canvas.parentElement.getBoundingClientRect();this.resizeCanvas(a.width,a.height)},get_height:function(){return this._canvas.height},get_width:function(){return this._canvas.width},
__class__:b.html.HtmlStage};b.html.HtmlUtil=function(){};b.html.HtmlUtil.__name__=!0;b.html.HtmlUtil.callLater=function(a,b){null==b&&(b=0);k.window.setTimeout(a,b)};b.html.HtmlUtil.hideMobileBrowser=function(){k.window.scrollTo(1,0)};b.html.HtmlUtil.loadExtension=function(a,e){null==e&&(e=k.window);var d=A.field(e,a);if(null!=d)return{prefix:null,field:a,value:d};for(var d=a.charAt(0).toUpperCase()+o.substr(a,1,null),f=0,g=b.html.HtmlUtil.VENDOR_PREFIXES;f<g.length;){var h=g[f];++f;var l=h+d,m=A.field(e,
l);if(null!=m)return{prefix:h,field:l,value:m}}return{prefix:null,field:null,value:null}};b.html.HtmlUtil.loadFirstExtension=function(a,e){for(var d=0;d<a.length;){var f=a[d];++d;f=b.html.HtmlUtil.loadExtension(f,e);if(null!=f.field)return f}return{prefix:null,field:null,value:null}};b.html.HtmlUtil.polyfill=function(a,e){null==e&&(e=k.window);var d=b.html.HtmlUtil.loadExtension(a,e).value;if(null==d)return!1;e[a]=d;return!0};b.html.HtmlUtil.setVendorStyle=function(a,e,d){for(var a=a.style,f=0,g=
b.html.HtmlUtil.VENDOR_PREFIXES;f<g.length;){var h=g[f];++f;a.setProperty("-"+h+"-"+e,d)}a.setProperty(e,d)};b.html.HtmlUtil.addVendorListener=function(a,e,d,f){for(var g=0,h=b.html.HtmlUtil.VENDOR_PREFIXES;g<h.length;){var k=h[g];++g;a.addEventListener(k+e,d,f)}a.addEventListener(e,d,f)};b.html.HtmlUtil.orientation=function(a){switch(a){case -90:case 90:return e.Orientation.Landscape;default:return e.Orientation.Portrait}};b.html.HtmlUtil.createEmptyCanvas=function(a,b){var d=k.document.createElement("canvas");
d.width=a;d.height=b;return d};b.html.HtmlUtil.createCanvas=function(a){var e=b.html.HtmlUtil.createEmptyCanvas(a.width,a.height),d=e.getContext("2d");d.save();d.globalCompositeOperation="copy";d.drawImage(a,0,0);d.restore();return e};b.html.WebAudioSound=function(a){this.buffer=a};b.html.WebAudioSound.__name__=!0;b.html.WebAudioSound.__interfaces__=[l.Sound];b.html.WebAudioSound.get_supported=function(){if(b.html.WebAudioSound._detectSupport){b.html.WebAudioSound._detectSupport=!1;var a=b.html.HtmlUtil.loadExtension("AudioContext").value;
null!=a&&(b.html.WebAudioSound.ctx=new a,b.html.WebAudioSound.gain=b.html.WebAudioSound.ctx.createGainNode(),b.html.WebAudioSound.gain.connect(b.html.WebAudioSound.ctx.destination),m.volume.watch(function(a){b.html.WebAudioSound.gain.gain.value=a}))}return null!=b.html.WebAudioSound.ctx};b.html.WebAudioSound.prototype={__class__:b.html.WebAudioSound};l={Director:function(){this._transitor=null}};l.Director.__name__=!0;l.Director.__super__=u;l.Director.prototype=v(u.prototype,{completeTransition:function(){null!=
this._transitor&&(this._transitor.complete(),this._transitor=null,this.invalidateVisibility())},invalidateVisibility:function(){for(var a=this.scenes.length;0<a;){var b=this.scenes[--a],b=b._compMap.Scene_4;if(null==b||b.opaque)break}this.occludedScenes=0<this.scenes.length?this.scenes.slice(a,this.scenes.length-1):[];b=this.get_topScene();null!=b&&this.show(b)},show:function(a){a=a._compMap.Scene_4;null!=a&&a.shown.emit0()},get_topScene:function(){var a=this.scenes.length;return 0<a?this.scenes[a-
1]:null},onUpdate:function(a){null!=this._transitor&&this._transitor.update(a)&&this.completeTransition()},onRemoved:function(){this.completeTransition();for(var a=0,b=this.scenes;a<b.length;){var d=b[a];++a;d.dispose()}this.scenes=[];this.occludedScenes=[];this._root.dispose()},onAdded:function(){this.owner.addChild(this._root)},get_name:function(){return"Director_3"},__class__:l.Director});l._Director={};l._Director.Transitor=function(){};l._Director.Transitor.__name__=!0;l._Director.Transitor.prototype=
{complete:function(){this._transition.complete();this._onComplete()},update:function(a){return this._transition.update(a)},__class__:l._Director.Transitor};l.Scene=function(){};l.Scene.__name__=!0;l.Scene.__super__=u;l.Scene.prototype=v(u.prototype,{get_name:function(){return"Scene_4"},__class__:l.Scene});l.Transition=function(){};l.Transition.__name__=!0;l.Transition.prototype={complete:function(){},update:function(){return!0},__class__:l.Transition};h.Promise=function(){this.success=new h.Signal1;
this.error=new h.Signal1;this.progressChanged=new h.Signal0;this.hasResult=!1;this._total=this._progress=0};h.Promise.__name__=!0;h.Promise.prototype={set_total:function(a){this._total!=a&&(this._total=a,this.progressChanged.emit0());return a},set_progress:function(a){this._progress!=a&&(this._progress=a,this.progressChanged.emit0());return a},get:function(a){return this.hasResult?(a(this._result),null):this.success.connect(a).once()},set_result:function(a){if(this.hasResult)throw"Promise result already assigned";
this._result=a;this.hasResult=!0;this.success.emit1(a);return a},__class__:h.Promise};h.Signal0=function(a){h.SignalBase.call(this,a)};h.Signal0.__name__=!0;h.Signal0.__super__=h.SignalBase;h.Signal0.prototype=v(h.SignalBase.prototype,{connect:function(a,b){null==b&&(b=!1);return this.connectImpl(a,b)},__class__:h.Signal0});h._SignalBase={};h._SignalBase.Task=function(a){this.next=null;this.fn=a};h._SignalBase.Task.__name__=!0;h._SignalBase.Task.prototype={__class__:h._SignalBase.Task};n=void 0;y=
void 0;y=function(){};y.__name__=!0;y.parse=function(a){return(new y).doParse(a)};y.prototype={parseNumber:function(a){for(var b=this.pos-1,d=45==a,e=!d,f=48==a,g=!1,h=!1,k=!1,l=!1;;){a=this.str.charCodeAt(this.pos++);switch(a){case 48:f&&!g&&this.invalidNumber(b);d&&(d=!1,f=!0);e=!0;break;case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:f&&!g&&this.invalidNumber(b);d&&(d=!1);e=!0;f=!1;break;case 46:(d||g)&&this.invalidNumber(b);e=!1;g=!0;break;case 101:case 69:(d||f||h)&&this.invalidNumber(b);
e=!1;h=!0;break;case 43:case 45:(!h||k)&&this.invalidNumber(b);e=!1;k=!0;break;default:e||this.invalidNumber(b),this.pos--,l=!0}if(l)break}a=w.parseFloat(o.substr(this.str,b,this.pos-b));b=a|0;return b==a?b:a},invalidNumber:function(a){throw"Invalid number at position "+a+": "+o.substr(this.str,a,this.pos-a);},parseString:function(){for(var a=this.pos,b=new G;;){var d=this.str.charCodeAt(this.pos++);if(34==d)break;if(92==d){b.addSub(this.str,a,this.pos-a-1);d=this.str.charCodeAt(this.pos++);switch(d){case 114:b.b+=
"\r";break;case 110:b.b+="\n";break;case 116:b.b+="\t";break;case 98:b.b+="\u0008";break;case 102:b.b+="\u000c";break;case 47:case 92:case 34:b.b+=String.fromCharCode(d);break;case 117:a=w.parseInt("0x"+o.substr(this.str,this.pos,4));this.pos+=4;b.b+=String.fromCharCode(a);break;default:throw"Invalid escape sequence \\"+String.fromCharCode(d)+" at position "+(this.pos-1);}a=this.pos}else if(d!=d)throw"Unclosed string";}b.addSub(this.str,a,this.pos-a-1);return b.b},parseRec:function(){for(;;){var a=
this.str.charCodeAt(this.pos++);switch(a){case 32:case 13:case 10:case 9:break;case 123:for(var b={},d=null,a=null;;){var e=this.str.charCodeAt(this.pos++);switch(e){case 32:case 13:case 10:case 9:break;case 125:return(null!=d||!1==a)&&this.invalidChar(),b;case 58:null==d&&this.invalidChar();b[d]=this.parseRec();d=null;a=!0;break;case 44:a?a=!1:this.invalidChar();break;case 34:a&&this.invalidChar();d=this.parseString();break;default:this.invalidChar()}}break;case 91:b=[];for(a=null;;)switch(e=this.str.charCodeAt(this.pos++),
e){case 32:case 13:case 10:case 9:break;case 93:return!1==a&&this.invalidChar(),b;case 44:a?a=!1:this.invalidChar();break;default:a&&this.invalidChar(),this.pos--,b.push(this.parseRec()),a=!0}break;case 116:a=this.pos;if(114!=this.str.charCodeAt(this.pos++)||117!=this.str.charCodeAt(this.pos++)||101!=this.str.charCodeAt(this.pos++))this.pos=a,this.invalidChar();return!0;case 102:a=this.pos;if(97!=this.str.charCodeAt(this.pos++)||108!=this.str.charCodeAt(this.pos++)||115!=this.str.charCodeAt(this.pos++)||
101!=this.str.charCodeAt(this.pos++))this.pos=a,this.invalidChar();return!1;case 110:a=this.pos;if(117!=this.str.charCodeAt(this.pos++)||108!=this.str.charCodeAt(this.pos++)||108!=this.str.charCodeAt(this.pos++))this.pos=a,this.invalidChar();return null;case 34:return this.parseString();case 48:case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:case 45:return this.parseNumber(a);default:this.invalidChar()}}},invalidChar:function(){this.pos--;throw"Invalid char "+this.str.charCodeAt(this.pos)+
" at position "+this.pos;},doParse:function(a){this.str=a;this.pos=0;return this.parseRec()},__class__:y};n={IntMap:function(){this.h={}}};n.IntMap.__name__=!0;n.IntMap.__interfaces__=[E];n.IntMap.prototype={remove:function(a){if(!this.h.hasOwnProperty(a))return!1;delete this.h[a];return!0},exists:function(a){return this.h.hasOwnProperty(a)},get:function(a){return this.h[a]},set:function(a,b){this.h[a]=b},__class__:n.IntMap};n.StringMap=function(){this.h={}};n.StringMap.__name__=!0;n.StringMap.__interfaces__=
[E];n.StringMap.prototype={iterator:function(){return{ref:this.h,it:this.keys(),hasNext:function(){return this.it.hasNext()},next:function(){return this.ref["$"+this.it.next()]}}},keys:function(){var a=[],b;for(b in this.h)this.h.hasOwnProperty(b)&&a.push(b.substr(1));return o.iter(a)},get:function(a){return this.h["$"+a]},set:function(a,b){this.h["$"+a]=b},__class__:n.StringMap};var M=0;Array.prototype.indexOf?o.remove=function(a,b){var d=a.indexOf(b);if(-1==d)return!1;a.splice(d,1);return!0}:null;
Math.__name__=["Math"];Math.NaN=Number.NaN;Math.NEGATIVE_INFINITY=Number.NEGATIVE_INFINITY;Math.POSITIVE_INFINITY=Number.POSITIVE_INFINITY;Math.isFinite=function(a){return isFinite(a)};Math.isNaN=function(a){return isNaN(a)};String.prototype.__class__=String;String.__name__=!0;Array.prototype.__class__=Array;Array.__name__=!0;Date.prototype.__class__=Date;Date.__name__=["Date"];var N={__name__:["Int"]},O={__name__:["Dynamic"]},K=Number;K.__name__=["Float"];var L=Boolean;L.__ename__=["Bool"];var P=
{__name__:["Class"]},Q={};"undefined"!=typeof JSON&&(y=JSON);b.html.HtmlPlatform.instance=new b.html.HtmlPlatform;h.SignalBase.DISPATCHING_SENTINEL=new h.SignalConnection(null,null);m.root=new x;m.uncaughtError=new h.Signal1;m.hidden=new h.Value(!1);m.hasGPU=new h.Value(!1);m.volume=new p.AnimatedFloat(1);m._platform=b.html.HtmlPlatform.instance;m._calledInit=!1;k.window="undefined"!=typeof window?window:null;k.document="undefined"!=typeof window?window.document:null;k.navigator="undefined"!=typeof window?
window.navigator:null;g.Manifest._buildManifest=g.Manifest.createBuildManifests();u=g.Manifest;E=(new z("\\b(Android)\\b","")).match(k.window.navigator.userAgent)?!1:null!=(new XMLHttpRequest).withCredentials;u._supportsCrossOrigin=E;e.Sprite._scratchPoint=new q.Point;e.Font.NEWLINE=new e.Glyph(10);b.BasicKeyboard._sharedEvent=new a.KeyboardEvent;b.BasicMouse._sharedEvent=new a.MouseEvent;b.BasicPointer._sharedEvent=new a.PointerEvent;b.html.CanvasRenderer.CANVAS_TEXTURES=(new z("(iPhone|iPod|iPad)",
"")).match(k.window.navigator.userAgent);b.html.HtmlAssetPackLoader._mediaRefCount=0;b.html.HtmlAssetPackLoader._detectBlobSupport=!0;b.html.HtmlUtil.VENDOR_PREFIXES=["webkit","moz","ms","o","khtml"];b.html.HtmlUtil.SHOULD_HIDE_MOBILE_BROWSER=k.window.top==k.window&&(new z("Mobile(/.*)? Safari","")).match(k.window.navigator.userAgent);b.html.WebAudioSound._detectSupport=!0;F.main()})();
